### PR TITLE
Feature/add tests and covarage to travis build

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@malirod
@AGaliuzov 
@AByzhynar 
Please Review

**Comment by AByzhynar** [comment]
Please edit 12aed1afe9c2438ef2d92a0dbe5aed6791bf8556 commit message. Enviromant -> environment. 
Reviewed.

**Comment by LuxoftAKutsan** [comment]
@AGaliuzov please review and merge

**Comment by JackLivio** [comment]
@LuxoftAKutsan What is codecov.io being used for? How can we see the reports it is collecting?

**Comment by LuxoftAKutsan** [comment]
@JackLivio codecov collects unit tests code coverage statistic, and reports about it's changing. Also there are a lot of sweet functionality like code coverage map, and it shows which  lines exactly covered by UT and which are not. 
Current develop branch code coverage is available by link https://codecov.io/gh/smartdevicelink/sdl_core/branch/develop 
Also codecov can collect statistics in pull request and say if it increased or decreased. You can find example in pull request #503

**Comment by JackLivio** [comment]
@LuxoftAKutsan Thank you very much!

**Pull request merged**
