### PR TITLE
New vehicle data - FuelRange feature

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
SDL implementation of new vehicle data - FuelRange feature

Proposal: [New vehicle data - FuelRange](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
Rebuild required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by AKalinich-Luxoft** [comment]
Rebased due to merge conflicts

**Comment by LitvinenkoIra** [comment]
Rebased due to merge conflicts

**Comment by theresalech** [comment]
This is a fix for #1656

**Comment by JackLivio** [comment]
Closed in favor of #2168

**Pull request closed without merging**
