### PR TITLE
fix to initialize 'app' variable in on_button_press_notification

### LINKED ISSUE #2116: onButtonPress notification is not sent to LIMITED state app
### Bug Report
onButtonPress notification is not sent to LIMITED state app

##### Reproduction Steps
1. App subscribes button
2. Set app HMI level to LIMITED
3. Send onButtonPress event from HMI to Core

##### Expected Behavior
onButtonPress event is sent to mobile

##### Observed Behavior
onButtonPress event is not sent to mobile

##### OS & Version Information
* OS/Version: iOS 5.1.1 / Android
* SDL Core Version: 4.4, 4.5
* Testing Against: Our internal HMI devboard and internal test mobile apps

##### Test Case, Sample Code, and / or Example App
I will create PR

### PR DESCRIPTION
**Pull request by t-yoshii**
Fixes #2116 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
I confirmed this PR fixes the issue in our internal HU devboard and internal test mobile app (iOS).

### Summary
'app' value is not initialized in OnButtonPressNotification::Run in non-CUSTOM_BUTTON code path. As a result, app.valid() always fails and onButtonPress notification is only sent to FULL state app. LIMITED state app cannot receive onButtonPress notification.

##### Bug Fixes
* Fix a bug that LIMITED state app cannot receive onButtonPress notification.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by t-yoshii** [comment]
Hi @jacobkeeler, thank you very much for your review.
I added your suggestion and confirmed to pass commands_test_unity.

**Comment by vkushnirenko-luxoft** [comment]
Due to check style, please run
./tools/infrastructure/check_style.sh

**Comment by t-yoshii** [comment]
Hi @vkushnirenko-luxoft thanks for your review. I fixed indent style.

**Comment by iCollin** [comment]
Hello @t-yoshii , thank you for submitting this issue and fix. In this PR the app variable is calculated once per app subscribed to OnButtonPress notifications which is unnecessary. I have created a new PR in place of this one based on latest develop where the app is calculated outside of the loop: https://github.com/smartdevicelink/sdl_core/pull/3378

**Pull request closed without merging**
