### PR TITLE
Cover HMI commands with Unit Tests. Part 15

### PR DESCRIPTION
**Pull request by wolfylambova22**
Following HMI commands were coverd by unit tests:

- vi_unsubscribe_vehicle_data_request
- vi_unsubscribe_vehicle_data_response
- vr_add_command_request
- vr_add_command_response
- vr_change_registration_request
- vr_change_registration_response
- vr_delete_command_request
- vr_delete_command_response

Related issue: APPLINK-25906

### CODE REVIEW

**Comment by wolfylambova22** [comment]
Please review: @vlantonov @AGaliuzov @AGritsevich @Kozoriz @LevchenkoS @VProdanov @dtrunov @orhan-mehmedov

**Comment by vlantonov** [comment]
@wolfylambova22 Reviewed

**Comment by orhan-mehmedov** [comment]
@wolfylambova22 Reviewed

**Comment by AGritsevich** [comment]
@wolfylambova22 Reviewed, but you have style problem. Look at CI server log.

**Comment by LevchenkoS** [comment]
@wolfylambova22, reviewed

**Comment by AGaliuzov** [comment]
@wolfylambova22 Reviewed

**Comment by VProdanov** [comment]
@wolfylambova22 Reviewed.

**Comment by dtrunov** [comment]
@wolfylambova22 Reviewed

**Comment by wolfylambova22** [comment]
@AGritsevich build seems to be terminated again, but PR is ready to be merged.

**Pull request merged**
