### PR TITLE
Feature/Pixel density and scale

### PR DESCRIPTION
**Pull request by IGapchuk**
Implements #2319

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Unit testing

### Summary
This PR provide changes for MOBILE_API and HMI_API.
Some navigation applications makes video stream using the screen resolution in pixel without knowing the screen size/pixel density. This can result into different behaviors on screens with the same size but different resolutions.

##### Breaking Changes
Add new parameters to VideoStreamingCapability structure:
- diagonalScreenSize - diagonal screen size of the screen;
- pixelPerInch - Pixel per inch (PPI) of the screen;
- scale - Scale value to determine how the app should scale
the captured view.

Add new parameters with default values to hmi_capabilities.json:
- diagonalScreenSize
- pixelPerInch
- scale

**Other parts of delivery:**
* HMI Integration guidelines: https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/pull/136
* SDL requirements: https://github.com/smartdevicelink/sdl_requirements/pull/128
* ATF scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2153
* HMI: https://github.com/smartdevicelink/sdl_hmi/pull/165

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by IGapchuk** [comment]
NOTE: feature branch has been rebased onto current develop

**Comment by IGapchuk** [comment]
@kshala-ford Please, be informed that feature branch has been rebased onto current develop. Feel free to approve it, or suggest required changes.

**Comment by kshala-ford** [comment]
@IGapchuk please remove other reviewers that didn't review yet.
@theresalech the PR is ready for review

**Comment by AStasiuk** [comment]
@kshala-ford other reviewers were removed.

**Comment by AStasiuk** [comment]
@theresalech, this PR is already reviewed and approved by Ford (by @kshala-ford) and ready for Livio review.

**Comment by IGapchuk** [comment]
Feature branch has been re-based onto current develop (c6e9a9bb55b14571d1f389c75b515a2c1c102f95)

**Comment by IGapchuk** [comment]
@kshala-ford @JackLivio Please be informed, that feature branch has been updated by a new commit (89cf4f00b5c44bc37e1b3c86905a66f55b8cb15e) that implements the revision https://github.com/smartdevicelink/sdl_evolution/pull/805.

**Pull request merged**
