### PR TITLE
SDL doesn't cut image in softbutton with "Type"=TEXT

### PR DESCRIPTION
**Pull request by dtrunov**
Fixed cutting image structure from softbutton with "TYPE"=TEXT
According with requirment at https://adc.luxoft.com/jira/browse/APPLINK-20270

Closes bug [APPLINK-26101](https://adc.luxoft.com/jira/browse/APPLINK-26101)

### CODE REVIEW

**Comment by dtrunov** [comment]
Please review @AGritsevich @AGaliuzov @OHerasym @dev-gh @wolfylambova22

**Comment by dev-gh** [comment]
Reviewed

**Comment by AGritsevich** [comment]
Reviewed

**Comment by wolfylambova22** [comment]
Reviewed.

**Comment by OHerasym** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
Reviewed

**Pull request merged**
