### PR TITLE
Feature/state controller refactoring

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
@anosach-luxoft @pestOO @AGaliuzov @malirod 
Please review

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
Rebased onto new develop. Resolved conflicts, please review.

**Comment by pestOO** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
