### PR TITLE
PTU triggers justify

### PR DESCRIPTION
**Pull request by dev-gh**
Justifying implementation of PTU triggers with open source.

Closes-bug: APPLINK-24500

### CODE REVIEW

**Comment by dev-gh** [comment]
@AGaliuzov 
Please review, but DO NOT merge until additional confirmation

**Comment by dev-gh** [comment]
@anosach-luxoft @VProdanov @vlantonov @OHerasym 
Please review

**Comment by vlantonov** [comment]
Reviewed

**Comment by malirod** [comment]
@dev-gh, please add JIRA link

**Comment by dev-gh** [comment]
@malirod 
Done

**Comment by VProdanov** [comment]
Reviewed

**Comment by dev-gh** [comment]
Will be re-sent to develop

**Pull request closed without merging**
