### PR TITLE
Fix/config profile tests on win

### PR DESCRIPTION
**Pull request by OHerasym**
### PR Changes: ###
- Fix ini_file issue 
- Fix config_profile tests

Related: [APPLINK-25520](https://adc.luxoft.com/jira/browse/APPLINK-25520)

### CODE REVIEW

**Comment by OHerasym** [comment]
@anosach-luxoft , @Kozoriz , @LuxoftAKutsan , @dtrunov , @VVeremjova , Please review

**Comment by Kozoriz** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Pull request merged**
