### PR TITLE
hotfix/Fix_Unit_Tests_for_Formatter_in_Genivi

### PR DESCRIPTION
**Pull request by OHerasym**
Enabled 2 UT in CFormatterJsonBase_test.cc

Related:
        APPLINK-17577

### CODE REVIEW

**Comment by monstersem** [comment]
Please review: @Kozoriz, @iAndrew5 , @pestOO , @VVeremjova

**Comment by pestOO** [comment]
Reviewed

**Comment by VVeremjova** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by iAndrew5** [comment]
Reviewed

**Comment by VVeremjova** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@OHerasym, are you sure we have to change code to fix tests?

**Comment by OHerasym** [comment]
@anosach-luxoft , all changes turned back ( UInt -> Int) in second commit. Tests were added without any changes, added UInt to SmartObject implementation, after conversation with Andrey Byzhynar.

**Comment by anosach-luxoft** [comment]
@OHerasym, please correct me if I'm not right but in `Files changed` tab I can see changes in files `smart_object.h` and `smart_object.cc`.

**Comment by OHerasym** [comment]
@anosach-luxoft , changes to smart_object were added from sdl_panasonic

**Pull request merged**
