### PR TITLE
Fix issue when in AlertManeuver TTS.Speak: appID parameter is not provided

### PR DESCRIPTION
**Pull request by kozlov-oleksandr**
- added param appID to message before sending HMI request
    in AlertManeuverRequest

### CODE REVIEW

**Comment by okozlovlux** [comment]
@LuxoftAKutsan @AByzhynar @indlu please review

**Comment by okozlovlux** [comment]
Rebuild required

**Comment by Itileda** [comment]
Rebuild required

**Comment by jacobkeeler** [comment]
Closed in favor of https://github.com/smartdevicelink/sdl_core/pull/3679

**Pull request closed without merging**
