### PR TITLE
Ubuntu 16.04 (and other modern Linux) Support

### PR DESCRIPTION
**Pull request by jacobkeeler**
Rework of #841 (originally made by @BTPankow) based off of the new develop branch.

This PR omits the change from auto_ptr to unique_ptr that was in the previous PR, so the project will still need to be compiled with the `-Wno-deprecated-declarations` flag until this change is made.

### CODE REVIEW

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan Can you quickly confirm again that these changes are good to merge?

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler , I have no issues due to code. 
@ OVVasyliev But I am worry about CI activities, Please check this pull request is able to build and run Unit tests

**Comment by mi-hol** [comment]
@LuxoftAKutsan you wanted '@ OVVasyliev ' to review CI process but this ID is not assigned to an active github user.
Was this perhaps a typo?

**Comment by jacobkeeler** [comment]
I found the security manager test to be Segfaulting on Ubuntu 16.04 due to it not supporting SSL3, so I just amended the commit with the fix. The test still fails (due to several cases using SSL3), but is much more clear about the reason now.

**Comment by jacobkeeler** [comment]
Just amended the commit once more, removing any tests which use SSLv3 if it is disabled. All unit tests now pass.

**Pull request merged**
