### PR TITLE
Create cmake global variable for install directory

### PR DESCRIPTION
**Pull request by anosach-luxoft**
Set platform-depend variable `INSTALL_DIRECTORY` in root `CMakeLists.txt` file to unify usages in components. Fixes incorrect install paths problem on Windows.

Related-issue: [APPLINK-25311](https://adc.luxoft.com/jira/browse/APPLINK-25311?filter=64331)

@LuxoftAKutsan, @dev-gh, @LevchenkoS, @Kozoriz, @nk0leg please review

### CODE REVIEW

**Comment by LevchenkoS** [comment]
@anosach-luxoft, reviewed

**Comment by anosach-luxoft** [comment]
@LuxoftAKutsan, @dev-gh, @Kozoriz, @nk0leg please review

**Comment by dev-gh** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by nk0leg** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@AGritsevich please merge

**Comment by AGritsevich** [comment]
@anosach-luxoft , done.

**Pull request merged**
