### PR TITLE
Feature/issue 2059 audio streaming indicator

### LINKED ISSUE #2059: [SDL 0109] SetAudioStreamingIndicator RPC
Proposal: [SetAudioStreamingIndicator RPC](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0109-set-audio-streaming-indicator.md)

> The proposal is about adding a new RPC for media apps to indicate the action of a play/pause button.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/334

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the revisions outlined in the [last comment](https://github.com/smartdevicelink/sdl_evolution/issues/334#issuecomment-346052274) from kshala-ford.

```xml
<function name="SetMediaClockTimer" messagetype="request">
  <param name="audioStreamingIndicator" type="AudioStreamingIndicator" mandatory="false" />
   :
</function>
```

>The Steering Committee also discussed the scenario when a head unit doesn't receive an update from the app, and it was determined that the head unit would fall back to old behavior in this case.

>The proposal .md was updated on March 14, 2018 to include the agreed upon revisions.

### PR DESCRIPTION
**Pull request by ashwink11**
Fixes #2059 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
ATF and unit tests

### Summary
Added AudioStreamingIndicator parameter in SetMediaClockTimer RPC

##### Breaking Changes
* [NA]

##### Enhancements
* [NA]

##### Bug Fixes
* [NA]

### Tasks Remaining:
- [X] [ATF scripts ] https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1924
- [X] [Unit Tests]

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ashwink11** [comment]
@jacobkeeler Please review the changes.

**Comment by theresalech** [comment]
@kshala-ford or @yang1070 please advise once this PR is ready for Livio review, and if there are any supporting PRs for this feature in other repositories.  Thanks!

**Comment by kshala-ford** [comment]
@theresalech the PR is ready for review. No there are no PRs ready for other repositorys yet.

**Comment by theresalech** [comment]
Thanks @kshala-ford!  Should we anticipate additional PRs for this feature in other repos?  We typically review all PRs related to a single feature together.

**Comment by kshala-ford** [comment]
@theresalech Oh. I'm sorry about that. The other pull requests should be ready by end of this week.

**Comment by ashwink11** [comment]
@yang1070 We did changes only for SDL core.

**Comment by kshala-ford** [comment]
@theresalech PRs for other repos are ready for review.

https://github.com/smartdevicelink/rpc_spec/pull/108
https://github.com/smartdevicelink/sdl_android/pull/800
https://github.com/smartdevicelink/sdl_ios/pull/1014

**Pull request merged**
