### PR TITLE
SDL does not resend appID and wayPointType in GetWayPoints rps to HMI

### PR DESCRIPTION
**Pull request by dtrunov**
Add parameters in mobile command

Closes bug [APPLINK-23766](https://adc.luxoft.com/jira/browse/APPLINK-23766)

### CODE REVIEW

**Comment by dtrunov** [comment]
Please review @AGaliuzov @OHerasym @AGritsevich @dev-gh

**Comment by AGritsevich** [comment]
Reviewed.

**Comment by pestOO** [comment]
@dtrunov, see [versioning agreements](https://adc.luxoft.com/confluence/display/APPLINK/API+xml+versioning+approach) and add one of the BA as a reviewer.

**Comment by dtrunov** [comment]
@AnastasiyaBritanova please review.

**Comment by AnastasiyaBritanova** [comment]
reviewed.

**Pull request merged**
