### PR TITLE
Temporary remove application manager commands tests

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Related issue : APPLINK-25547

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@anosach-luxoft @LevchenkoS @AGritsevich @okozlovlux

**Comment by okozlovlux** [comment]
@LuxoftAKutsan , reviewed

**Comment by LevchenkoS** [comment]
@LuxoftAKutsan, reviewed.

**Comment by AGritsevich** [comment]
@LuxoftAKutsan , reviewed

**Pull request merged**
