### PR TITLE
Move HMI commands missed tests from release/4.3.0 to develop

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Move HMI commands missed tests from release/4.3.0 to develop
Raise covered to 65%.

Comment application_manager_impl_test to increase coverage
application_manager_impl_test includes to statistics additional files, that are not fully covered.
Raise covered to 73.1%.

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@LuxoftAKutsan please review

**Comment by LuxoftAKutsan** [comment]
@LitvinenkoIra please manage with buils issues

**Comment by LitvinenkoIra** [comment]
Rebuild required

**Comment by LuxoftAKutsan** [comment]
Rebuild required

**Pull request merged**
