### PR TITLE
SDL does not resend appID and wayPointType in GetWayPoints rps to HMI

### PR DESCRIPTION
**Pull request by dtrunov**
Add parameters in mobile command

Closes bug [APPLINK-23766](https://adc.luxoft.com/jira/browse/APPLINK-23766)

### CODE REVIEW

**Comment by dtrunov** [comment]
Please review @AGaliuzov @OHerasym @AGritsevich @Anatoliy-Leshin @dev-gh

**Comment by AGritsevich** [comment]
Reviewed.

**Comment by OHerasym** [comment]
Reviewed.

**Comment by Anatoliy-Leshin** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by dtrunov** [comment]
@AnastasiyaBritanova pleas review.

**Comment by AnastasiyaBritanova** [comment]
reviewed.

**Pull request merged**
