### PR TITLE
Fix Policy Update flow for EXTERNAL_PROPRIETARY

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
SDL should send file with policy update also in EXTERNAL_PROPRIETARY

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler @JackLivio this defect is present in develop. Do we plan to fix it?

**Comment by JackLivio** [comment]
@LuxoftAKutsan I think you might have mentioned this before but where is binary data attached to an onSystemRequest in the case that core is built with HTTP policies?

**Comment by JackLivio** [comment]
Never mind I found it. Approved!

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan please rebase on and target develop

**Comment by jacobkeeler** [comment]
@LuxoftAKutsan never mind, it appears that this fix was merged in as part of #1529, this PR can be closed

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler sorry for long out of attention. Thanks!

**Pull request closed without merging**
