### PR TITLE
Feature/sdl 0285 ShowConstantTBT update

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Implements https://github.com/smartdevicelink/sdl_core/issues/3589

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Summary
Updates the descriptions of ShowConstantTBT's parameters `distanceToManeuver` and `distanceToManeuverScale` in the MOBILE and HMI API's

rpc_spec from https://github.com/smartdevicelink/rpc_spec/pull/304

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by MichaelCrimando** [comment]
Original author of the proposal here. Looks good to me!

**Comment by LitvinenkoIra** [comment]
@JackLivio This PR is ready for Livio ready. Thank you!

**Review by jacobkeeler — APPROVED** [review]

**Comment by jacobkeeler** [comment]
@LitvinenkoIra please fix conflicts

**Comment by LitvinenkoIra** [comment]
@jacobkeeler Done in b4b474c

**Pull request merged**
