### PR TITLE
Move media pipe creation before StartStream command

### PR DESCRIPTION
**Pull request by asenkk**
Before this change, streaming pipe was not created when we start
streamning service and send pipe URI to HMI in StartStream, but only
when the streaming begins. So the HMI may try to open a non-existing
pipe when it receives pipe URI.
To fix this moved pipe creation from PipeStreamer::Connect() to
PipeStreamer::PipeStreamer() and pipe unlink from
PipeStreamer::Disconnect() to PipeStreamer::~PipeStreamer().
Thus the pipes are created when SDL starts and media manager is
initialized.

Fixes: APPLINK-20018

### CODE REVIEW

**Comment by asenkk** [comment]
@AGaliuzov , @AGritsevich , @Anatoliy-Leshin , @VProdanov please review

**Comment by Anatoliy-Leshin** [comment]
Reviewed

**Comment by AGritsevich** [comment]
@asenkk , did you check it on build server?

**Comment by asenkk** [comment]
@AGritsevich , no, I compiled and tested manually.

**Comment by AGritsevich** [comment]
With unit tests?

On 18.02.2016 15:13, Asen Kirov wrote:

@AGritsevich<https://github.com/AGritsevich> , no, I compiled and tested manually.

—
Reply to this email directly or view it on GitHub<https://github.com/smartdevicelink/sdl_core/pull/396#issuecomment-185712323>.

--

Kind regards,

Anton Hrytsevich

Software Developer, Luxoft Odessa

T: +38 (048) 720 7001 M: +38(066)500 97 29

________________________________

This e-mail and any attachment(s) are intended only for the recipient(s) named above and others who have been specifically authorized to receive them. They may contain confidential information. If you are not the intended recipient, please do not read this email or its attachment(s). Furthermore, you are hereby notified that any dissemination, distribution or copying of this e-mail and any attachment(s) is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender by replying to this e-mail and then delete this e-mail and any attachment(s) or copies thereof from your system. Thank you.

**Comment by asenkk** [comment]
No, with real SPT, SDL and HMI.

**Comment by asenkk** [comment]
When running the tests manually connection_handler_test fails in about 50% of the runs, but this was happening without my last changes also.

**Comment by AGritsevich** [comment]
Reviewed.

**Comment by VProdanov** [comment]
Reviewed.

**Pull request merged**
