### PR TITLE
Cover HMI notifications with unit tests

### PR DESCRIPTION
**Pull request by okozlovlux**
Covered files \src\components\application_manager\src\commands\hmi\on_*.cc
 Added some smart_objects to smart_oblects.h
 Added template unit tests for similar commands

Related to APPLINK-23477

@LevchenkoS @AByzhynar @Kozoriz @vlantonov @anosach-luxoft please review

Previous pull request [https://github.com/smartdevicelink/sdl_core/pull/602]. Fixed issue with Qt build

### CODE REVIEW

**Comment by AByzhynar** [comment]
Reviewed

**Comment by LevchenkoS** [comment]
@okozlovlux, reviewed.

**Comment by Kozoriz** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by vlantonov** [comment]
@okozlovlux Reviewed

**Comment by okozlovlux** [comment]
Pull request doesn't merge and close, because Travis CI stops build with timeout, even build is successfull.

**Comment by AByzhynar** [comment]
@okozlovlux I am ready to merge this PR but can not understand 
>  Pull request doesn't merge and close, because Travis CI stops build with timeout, even build is successfull.

**Comment by okozlovlux** [comment]
@AByzhynar this comment was added for avoiding get a metric, when Travis CI build was faillig with timeout and this PR was not be able to merge. 
A. Leshin asked to add this comment.

**Pull request merged**
