### PR TITLE
Add Telnet logging

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
ATF can't collect logs via SocketHub or socket because of specific log4cxx binary format of logs
ATF can collect logs from TelnetAppender, that send is as plain text
Add to log4cxx.properties logging via telnet to collect this logs with ATF

Related Issues: APPLINK-14183

### CODE REVIEW

**Comment by AGaliuzov** [comment]
Why ATF related PR has been sent to this place?

**Comment by LuxoftAKutsan** [comment]
What is PR?
ATF should work with GENIVI SDL version too.

**Comment by AGaliuzov** [comment]
Are there any requirements about this?
I mean no one in opensource aware about ATF, so i make a sense to remove this word from commit message

**Comment by AGaliuzov** [comment]
Bacause actually these changes are not related to ATF directly it is just extensions for the logger

**Comment by justinjdickow** [comment]
@LuxoftAKutsan PR is "Pull Request"

@AGaliuzov Wondering if this is good as a hotfix or if it should be on develop. It doesn't effect SDL functionality so either place is fine with me

**Comment by LuxoftAKutsan** [comment]
Notes taken into account and pull request recreated https://github.com/smartdevicelink/sdl_core/pull/164

**Pull request closed without merging**
