### PR TITLE
Add new parameter named `auto_complete_list`

### PR DESCRIPTION
**Pull request by LevchenkoS**
SDL must support and process new `autoCompleteList` param at `SetGlobalProperties` RPC
##
@okozlovlux, @indlu, @dcherniev, @LitvinenkoIra, please, review.

### CODE REVIEW

**Comment by LevchenkoS** [comment]
Rebuild required

**Comment by LevchenkoS** [comment]
Rebuild required

**Comment by LevchenkoS** [comment]
Rebuild required

**Comment by jacobkeeler** [comment]
Related: #1858

**Comment by jacobkeeler** [comment]
closing in favor of #2959

**Pull request closed without merging**
