### PR TITLE
Check styler script update

### PR DESCRIPTION
**Pull request by pestOO**
Add clang-formater check and install hint
Add help command and description

### CODE REVIEW

**Comment by pestOO** [comment]
@AByzhynar, please review

**Comment by AByzhynar** [comment]
@pestOO I am not sure that it's a good idea to put clang-format installation into this script. I discussed it earlier with @LuxoftAKutsan and get reply that this installation should be made in setup_env script. 
So check_style.sh must only check style.

**Comment by pestOO** [comment]
@AByzhynar 
I haven't add installing, only *instruction* of installing was added.
So, It only checks style (or fix)

**Comment by AByzhynar** [comment]
@pestOO Reviewed

**Comment by pestOO** [comment]
@anosach-luxoft, @AGaliuzov, please merge

**Comment by pestOO** [comment]
@anosach-luxoft, @AGaliuzov, please merge

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by pestOO** [comment]
@AByzhynar, @AGritsevich, @anosach-luxoft, @AGaliuzov, please merge

**Comment by pestOO** [comment]
@AByzhynar, @AGritsevich, @anosach-luxoft, @AGaliuzov, please merge

**Comment by AGritsevich** [comment]
@pestOO, your build changes fail on QT build. According our merge rules, all builds have to be successful. Your QT build fail due some problem on CI server, I'd restarted it. It take about 15-20 min. When it finished successfully, I'll merge it. Thank you for your patience.

**Comment by pestOO** [comment]
@AGritsevich, thanks!

**Pull request merged**
