### PR TITLE
state_controller sdd

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Not required 

### Summary
Design for state  for state controller

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@theresalech please take a look at this PR.
It contains only documentation for existing architecture.

**Comment by theresalech** [comment]
@LuxoftAKutsan, can you please submit a PR to the `sdl_core_guides` repo with this information?  It will fit under the `Developer Documentation` section.  Thanks!

**Comment by LuxoftAKutsan** [comment]
@theresalech should I choose some other format instead of Doxygen in sdl_core guides?
I supposed to see the described information in http://sdl-core-doxygen-documentation.s3.amazonaws.com/index.html after merging. 
But we can choose another format if it fits way how we manage detailed documentation

**Comment by theresalech** [comment]
Hi @LuxoftAKutsan , good question!  Yes, the SDL Core Guides are written in DocDown.  You can find more information about styling and formatting in the [README](https://github.com/smartdevicelink/sdl_core_guides/blob/master/README.md).

**Comment by theresalech** [comment]
Closing this issue based on the conversation above.  @LuxoftAKutsan, please tag me on the SDL Core Guides PR once it is ready for Livio review.  Thanks!

**Pull request closed without merging**
