### PR TITLE
Change jenkins status link

### PR DESCRIPTION
**Pull request by vkushnirenko-luxoft**
This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Summary
Fix CI status link

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by vkushnirenko-luxoft** [comment]
Request required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by jacobkeeler** [comment]
Duplicate of https://github.com/smartdevicelink/sdl_core/pull/2525

**Pull request closed without merging**
