### PR TITLE
Fix sending to HMI tts_name and vrSynonyms in UpdateAppList.

### PR DESCRIPTION
**Pull request by Anatoliy-Leshin**
Fix sending to HMI tts_name and vrSynonyms in UpdateAppList.

### CODE REVIEW

**Comment by Anatoliy-Leshin** [comment]
Please, review @AGaliuzov  @pestOO @dev-gh

**Comment by Anatoliy-Leshin** [comment]
Please, review @AGaliuzov @pestOO @dev-gh

**Comment by pestOO** [comment]
Reviwed

**Comment by AGaliuzov** [comment]
Reviewed

**Pull request merged**
