### PR TITLE
Add dynamic links with build statuses for QT and Windows native builds

### PR DESCRIPTION
**Pull request by AByzhynar**
Added dynamic links with statuses of QT and Windows native builds
Added name for every build configuration

Related: [APPLINK-25517](https://adc.luxoft.com/jira/browse/APPLINK-25517)

### CODE REVIEW

**Comment by AByzhynar** [comment]
@okozlovlux @LevchenkoS @dev-gh @nk0leg Please review

**Comment by dev-gh** [comment]
Reviewed

**Comment by LevchenkoS** [comment]
@AByzhynar, reviewed.

**Comment by nk0leg** [comment]
Reviewed

**Comment by okozlovlux** [comment]
@AByzhynar reviewed

**Comment by AByzhynar** [comment]
@anosach-luxoft Please merge

**Pull request merged**
