### PR TITLE
Initial pull-request from rsdl sub repository

### PR DESCRIPTION
**Pull request by pvysh9**
Includes source code for releases up to E2.7 (including).

### CODE REVIEW

**Comment by AGaliuzov** [comment]
Are you sure that this is proper place for this pull request?

**Comment by AGaliuzov** [comment]
@justinjdickow, do we really need this PR?

**Comment by justinjdickow** [comment]
@AGaliuzov It's probably better to be submitted against the branch it actually tracks. I believe it's supposed to be against release/4.0.0? I will have a discussion with that team about where they based their PR.

**Comment by AByzhynar** [comment]
Build triggered. sha1 is merged.

**Comment by AByzhynar** [comment]
Build started sha1 is merged.

**Comment by AByzhynar** [comment]
Build finished.

**Pull request closed without merging**
