### PR TITLE
Change post-increments to pre-increments

### LINKED ISSUE #2314: Change post-increments to pre-increments
### Introduction

Post-increments on iterators may be the reason of performance leaks. Also pre-increments are required by the [Google styleguide](https://google.github.io/styleguide/cppguide.html#Preincrement_and_Predecrement).

### Motivation

When a variable is incremented (++i or i++) or decremented (--i or i--) and the value of the expression is not used, one must decide whether to preincrement (decrement) or postincrement (decrement).
When the return value is ignored, the "pre" form (++i) is never less efficient than the "post" form (i++), and is often more efficient. This is because post-increment (or decrement) requires a copy of i to be made, which is the value of the expression. If i is an iterator or other non-scalar type, copying i could be expensive.

### Proposed solution

The issue is about to change the all post-increment to pre-increment because it will save the memory and won't to copy the object.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2314 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Change post-increments to pre-increments by the google style.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
@ValeriiMalkov please check the UTs  app_launch_ctrl_test ................***Exception: SegFault

**Comment by malkofff** [comment]
Rebuild required

**Comment by iCollin** [comment]
Since this PR is now from `unknown repository` and has conflicts, it has been closed.

Many of the changes were implemented in https://github.com/smartdevicelink/sdl_core/pull/3687.

**Pull request closed without merging**
