### PR TITLE
Update generate_test_certificates.py script

### PR DESCRIPTION
**Pull request by LevchenkoS**
Previously SDL was implemented in the way to support certificate in PKCS12
Now it has been changed to simple PEM format according to the new requirements.

@pold500, @indlu, @tkireva, @LuxoftAKutsan, please, review.

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@LevchenkoS please add more detailed description

**Comment by tkireva** [comment]
@LevchenkoS Is it possible failed unit test to be related to these changes?

**Comment by LevchenkoS** [comment]
@tkireva, UT failure fixed

**Comment by LuxoftAKutsan** [comment]
@AGaliuzov @dev-gh please also take a look

**Comment by LevchenkoS** [comment]
Rebuild required

**Comment by istoilovgithub** [comment]
@LevchenkoS @LuxoftAKutsan Hey Guys, I am just curious why did we missed to sync up on this topic, one of my [PR](https://github.com/smartdevicelink/sdl_core/pull/1414) addresses exactly the same issue. It would be nice to such situations in the future by communicating more efficiently.

**Pull request merged**
