### PR TITLE
UnitTests_Fix_in_transportManager

### PR DESCRIPTION
**Pull request by Kozoriz**
1. Changed virtuality of 2 methods =>
		Fixed 4 unit tests in tcp_transport_adapter_test
	2. Removed 2 unit tests in transport_manager_impl_test
		(functionality is absent)

	Related : APPLINK-17584

### CODE REVIEW

**Comment by Kozoriz** [comment]
please review : @AGaliuzov , @Anatoliy-Leshin

**Comment by Anatoliy-Leshin** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
We also have `OVERRIDE` macro, I would suggest to use it with virtual keyword whenever it possible

**Comment by AGaliuzov** [comment]
Also, branch name is wrong, you need to add either `hotfix/` or `fetaure/`

**Pull request closed without merging**
