### PR TITLE
SDD documentation example

### PR DESCRIPTION
**Pull request by pestOO**
Updated Doxygen config file
Remove legacy doc files from policy folder
Add SDD Template
Add Security SDD version as an example.

For more information, please follow [article](https://github.com/smartdevicelink/sdl_core/wiki/Providing-design-documentation-with-code-changes).

Related issue: [APPLINK-25051](https://adc.luxoft.com/jira/browse/APPLINK-25051)

### CODE REVIEW

**Comment by pestOO** [comment]
@AGaliuzov, @LuxoftAKutsan, @anosach-luxoft,
Please review

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by pestOO** [comment]
@LuxoftAKutsan,
Please review and merge.

**Comment by LuxoftAKutsan** [comment]
@pestOO are you sure that dox is best solution fr SAD?

**Comment by pestOO** [comment]
@LuxoftAKutsan,
According to Doxygen config file it could be `dox`. 
Also our 3-dparty libraries are using `dox` exrention for Doxygen documentation files:
* https://github.com/smartdevicelink/sdl_core/blob/master/src/3rd_party/apache-log4cxx-0.10.0/src/site/doxy/mainpage.dox
* https://github.com/smartdevicelink/sdl_core/blob/master/src/3rd_party-static/jsoncpp/doc/jsoncpp.dox
* https://github.com/smartdevicelink/sdl_core/blob/master/src/3rd_party-static/jsoncpp/doc/roadmap.dox

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Pull request merged**
