### PR TITLE
hotfix/Fix_encryption_of_multiframe_message

### PR DESCRIPTION
**Pull request by VProdanov**
- Add decryption of the payload data of FRAME_TYPE_FIRST in
multiframe messages.

Related Issues: 
                APPLINK-13960
		APPLINK-13957

### CODE REVIEW

**Comment by VProdanov** [comment]
Please review @AGaliuzov, @nk0leg, @dev-gh, @AGritsevich

**Comment by dev-gh** [comment]
Reviewed

**Comment by AGritsevich** [comment]
Reviewed

**Comment by nk0leg** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
@VProdanov has to be rebased

**Pull request closed without merging**
