### PR TITLE
Cover some commands with UT

### PR DESCRIPTION
**Pull request by okozlovlux**
- fully covered some commands with UT

Related to [APPLINK-28068](https://adc.luxoft.com/jira/browse/APPLINK-28068)

### CODE REVIEW

**Comment by okozlovlux** [comment]
@OHerasym @dtrunov @LevchenkoS @wolfylambova22 @pvvasilev @Kozoriz please review

**Comment by okozlovlux** [comment]
@OHerasym @LevchenkoS @Kozoriz please review

**Comment by AByzhynar** [comment]
@okozlovlux According the rules at least one Senior developer must proceed with any code review, especially for junior developer code

**Comment by AByzhynar** [comment]
@okozlovlux Commit body must have more concrete information in its body.

**Comment by okozlovlux** [comment]
@AByzhynar , added info in 63a2df0

**Pull request merged**
