### PR TITLE
Complete unit tests for policy handler

### PR DESCRIPTION
**Pull request by VVeremjova**
Please review @okozlovlux, @dtrunov, @LevchenkoS
Related to [APPLINK-20088](https://adc.luxoft.com/jira/browse/APPLINK-20088)

### CODE REVIEW

**Comment by okozlovlux** [comment]
@LuxoftAKutsan reviewed

**Comment by LevchenkoS** [comment]
@VVeremjova reviewed

**Comment by dtrunov** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@OHerasym, @VProdanov please review

**Comment by OHerasym** [comment]
Reviewed

**Comment by VProdanov** [comment]
@VVeremjova  policy_handler_test.cc I noticed class members variables without "_" at the end, also I noticed string class variables with CamelCase names, please check. Could you please check this file with cpplint for style complatability.

**Comment by VProdanov** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@VProdanov See 1f9bfb4

**Pull request merged**
