### PR TITLE
Add information about SDL Coding Style

### PR DESCRIPTION
**Pull request by AByzhynar**
Changed encoding of COMMITERS.md to UNIX
Added information about Coding Style used in SDL

Related: [APPLINK-24614](https://adc.luxoft.com/jira/browse/APPLINK-24614)

### CODE REVIEW

**Comment by AByzhynar** [comment]
@okozlovlux @nk0leg @LevchenkoS @dev-gh @LuxoftAKutsan please review

**Comment by LevchenkoS** [comment]
@AByzhynar, reviewed.

**Comment by okozlovlux** [comment]
@AByzhynar , reviewed

**Comment by nk0leg** [comment]
@AByzhynar, reviewed.

**Comment by LuxoftAKutsan** [comment]
Why you merged  you chages and encoding issus in one commit?

**Comment by dev-gh** [comment]
Reviewed

**Comment by AByzhynar** [comment]
@LuxoftAKutsan Fixed. Commits divided into separate ones.

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by AByzhynar** [comment]
@anosach-luxoft Please merge

**Pull request merged**
