### PR TITLE
PolicyTableUpdate must be triggered in case no "certificate" exist at "module_config" section of PolicyTable"

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Implementation of [#1046](https://github.com/smartdevicelink/sdl_core/issues/1046)

### CODE REVIEW

**Comment by jacobkeeler** [comment]
Please rebase on new develop

**Comment by AByzhynar** [comment]
@jacobkeeler Can not reproduce the defect.
Please specify:
- transport type (usb, bluetooth or Wifi) 
- Mobile application (name and version)
- Add logs and core file if possible.
- HMI version

**Comment by jacobkeeler** [comment]
@AByzhynar Apologies, I have determined that the crash only happens on Ubuntu 16.04 rather than 14.04.

If you can still use the information:

Commit: d7f6854338d278aea65c4485773ee32de9e573dd
Application: SPT, 20170602-Nightly-Android
Transport: Wifi
Logs: [SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/1056386/SmartDeviceLinkCore.txt)
SDL HMI commit: ec37b1bd52c51218bfa1d2abae75ff07ce38380c

**Comment by AByzhynar** [comment]
@jacobkeeler As I can see from your logs: 
```
INFO  [02 Jun 2017 09:03:55,334][0x7f60fa070780][SDLMain] /home/jacobkeeler/Documents/sdl_core/src/appMain/main.cc:146 main: Application started!

TRACE [02 Jun 2017 09:18:04,434][0x7f60fa0ae700][ProtocolHandler] /home/jacobkeeler/Documents/sdl_core/src/components/protocol_handler/src/protocol_handler_impl.cc:885 
RESULT_CODE protocol_handler::ProtocolHandlerImpl::HandleControlMessage: FrameData: StartService


TRACE [02 Jun 2017 09:18:20,288][0x7f60fa0ae700][ProtocolHandler] /home/jacobkeeler/Documents/sdl_core/src/components/protocol_handler/src/protocol_handler_impl.cc:885 RESULT_CODE protocol_handler::ProtocolHandlerImpl::HandleControlMessage: FrameData: StartService
TRACE [02 Jun 2017 09:18:20,288][0x7f60fa0ae700][ProtocolHandler] /home/jacobkeeler/Documents/sdl_core/src/components/protocol_handler/src/protocol_handler_impl.cc:1068 RESULT_CODE protocol_handler::ProtocolHandlerImpl::HandleControlMessageStartSession: Enter
DEBUG [02 Jun 2017 09:18:20,288][0x7f60fa0ae700][ProtocolHandler] /home/jacobkeeler/Documents/sdl_core/src/components/protocol_handler/src/protocol_handler_impl.cc:1071 RESULT_CODE protocol_handler::ProtocolHandlerImpl::HandleControlMessageStartSession: Protocol version:4
TRACE [02 Jun 2017 09:18:20,288][0x7f60fa0ae700][ConnectionHandler] /home/jacobkeeler/Documents/sdl_core/src/components/connection_handler/src/connection_handler_impl.cc:288 ConnectionHandlerImpl::OnSessionStartedCallback: Enter
DEBUG [02 Jun 2017 09:18:20,288][0x7f60fa0ae700][ConnectionHandler] /home/jacobkeeler/Documents/sdl_core/src/components/connection_handler/src/connection_handler_impl.cc:277 AllowProtection: Service 10 allowed


DEBUG [02 Jun 2017 10:15:22,468][0x7f60fa070780][SDLMain] /home/jacobkeeler/Documents/sdl_core/src/appMain/life_cycle.cc:299 {anonymous}::sig_handler: SIGINT signal has been caught
TRACE [02 Jun 2017 10:15:22,468][0x7f60fa070780][SDLMain] /home/jacobkeeler/Documents/sdl_core/src/appMain/life_cycle.cc:318 LifeCycle::Run: Exit
INFO  [02 Jun 2017 10:15:22,468][0x7f60fa070780][SDLMain] /home/jacobkeeler/Documents/sdl_core/src/appMain/main.cc:194 main: Stop SDL due to caught signal
TRACE [02 Jun 2017 10:15:22,468][0x7f60fa070780][SDLMain] /home/jacobkeeler/Documents/sdl_core/src/appMain/life_cycle.cc:327 LifeCycle::StopComponents: Enter
```
You have started AudioService at 9:18:20 and the SDL continued working for next 57 minutes until somebody sent SIGINT signal (Ctrl+C keys combination) and SDL stops. I can not see core crash. 

Also I can not reproduce it . Env used: 
OS: Ubuntu 16.04 x64
SDL commit: d7f6854338d278aea65c4485773ee32de9e573dd
Mobile Application: SPT, 20170602-Nightly-Android
SDL HMI commit: ec37b1bd52c51218bfa1d2abae75ff07ce38380c
Transport used:  Bluetooth, USB and WiFi transport
Log file: 
[SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/1057936/SmartDeviceLinkCore.txt)
See logs, please.

**Comment by jacobkeeler** [comment]
@AByzhynar I'm very sorry, I sent you a log from another build:

Here is the actual log: [SmartDeviceLinkCore.txt](https://github.com/smartdevicelink/sdl_core/files/1058096/SmartDeviceLinkCore.txt)

**Comment by AByzhynar** [comment]
@jacobkeeler Please provide the core file . As I can not reproduce it locally - I need to analyze your core file to determine core crash reason and fix it.

**Comment by jacobkeeler** [comment]
Comment was updated

**Comment by AByzhynar** [comment]
@jacobkeeler Could you be so kind and attach core file (core dump file)? 
Steps to get it: 
1) In directory where executable `smartDeviceLinkCore` located run the following command: 
**ulimit -c unlimited**
2) Start SDL , if SDL core crashes - check the directory contents. You should have file with the name `core`. Please attach it. Thanks a lot.

**Comment by AByzhynar** [comment]
@dev-gh Please check if you can reproduce the defect posted.

**Comment by LitvinenkoIra** [comment]
Replaced by #1971

**Pull request closed without merging**
