### PR TITLE
Feature/complete ut for policy

### PR DESCRIPTION
**Pull request by VVeremjova**
Changed int type in cache manager to proper uint
Wrote unit tests for GetNotificationsNumber
Added tests from pasa repository

Relates to APPLINK-20072

Please review : @malirod @anosach-luxoft @AByzhynar @Kozoriz @OHerasym @AMikhniev
This is the same code for Genivi from CustomSDL/sdl_panasonic/pull/163

### CODE REVIEW

**Comment by AMikhniev** [comment]
Reviewed

**Comment by Kozoriz** [comment]
reviewed

**Comment by OHerasym** [comment]
reviewed

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
