### PR TITLE
Fix logger build on windows

### PR DESCRIPTION
**Pull request by anosach-luxoft**
@nk0leg, @LuxoftAKutsan, @dev-gh, @LevchenkoS, @Kozoriz please review

### CODE REVIEW

**Comment by LevchenkoS** [comment]
@anosach-luxoft, reviewed.

**Comment by dev-gh** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
reviewed

**Comment by nk0leg** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@AGritsevich please merge

**Pull request merged**
