### PR TITLE
fix SDL Crash seen in SDL upon receiving rpc - OnEmergencyEvent with "enabled:true"

### LINKED ISSUE #2808: [SDL] Crash seen in SDL upon receiving rpc - OnEmergencyEvent with "enabled:true"
### Bug Report
When the app is getting registered, if SDL receives rpc OnEmergencyEvent with "enabled:true", then there is assert failure in UsageStatistics::RecordHmiStateChanged(HMILevel::eType new_hmi_level) due to hmi_level -1 i.e. INVALID_ENUM

##### Reproduction Steps
1. Sygic app is launched on the phone.
2. Connect the Android phone to HU over USB. 
3. At the same time SDL receives rpc  - OnEmergencyEvent with "enabled:true" from HMI.

######Note
Make sure that OnEmergencyEvent with enabled:true is received by SDL at the time when app is getting registered.

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashes with DCHECK failure 

##### OS & Version Information
* OS/Version: Android 8.0.0
* SDL Core Version: 4.2

##### Test Case, Sample Code, and / or Example App
[SDLBacktrace.txt](https://github.com/smartdevicelink/sdl_core/files/2840500/SDLBacktrace.txt)
[SDLLogs.txt](https://github.com/smartdevicelink/sdl_core/files/2840501/SDLLogs.txt)

Please let us know if more information is required.

### PR DESCRIPTION
**Pull request by zhouxin627**
Fixes #2808 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by manual testing

### Summary
SDLCore received `OnAppRegistered` RPC. There contain 2 steps:
1. `application_manager` add Application to the list of registered applications.
2. change Application `HMILevel` from `INVALID_ENUM` to the default value.
The issue occurs time is between step 1 and step 2, HMI send `OnEmergencyEvent(true)` RPC to SDLCore at this time, which cause Application new `HMILevel` change 
to `INVALID_ENUM`，then SDL crashes with `DCHECK` failure in `RecordHmiStateChanged` function because new `HMILevel` is `INVALID_ENUM`. 
image
Code modification are as follows:				

- If some application‘s `HMILevel` value is `INVALID_ENUM`, SDLCore should not change `HMILevel` to any valid `HMILevel` in `hmi_state.cc`					

 (In order to avoid `HMILevel`  has incorrect change in some cases，for example, HMI sends a `OnEventChanged(DEACTIVATE_HMI)` event to SDLCore when the `HMILevel` is `INVALID_ENUM`, 						
which will cause `HMILevel` value change to `BACKGROUND`  from `INVALID_ENUM`, as result,  SDLCore will send `OnHmiStatus(BACKGROUND)` to mobileApp）						

- If some application‘s old `HMILevel` and new `HMILevel` are both `INVALID_ENUM`(Invalid value), SDLCore should not run `OnStateChanged` function to avoid `DCHECK` failure.					

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by zhouxin627** [comment]
Hi @LuxoftAKutsan, thank you for your comment.
We suppose that the root solution to the issue is that not add App to `AppList` before `HMILevel` initialization, the process of `AppRegistering` should be adjusted as follows：
1. Initialize App `HMILevel`
2. Add App to `AppList`

This change maybe has great influence and cause new issues to SDLCore,
because it is not known which functions of SDLCore depend on the old registration process.
For example, now App always receives `RegisterAppInterfaceResponse` RPC before receiving `HMILevel` RPC.
If SDLCore Initialize `HMILevel` before App adds to `AppList`, then `OnHMIStatus` RPC will send to App after `HMILevel` initialization,
`RegisterAppInterfaceResponse` RPC will send to App after app added to `AppList`,
This will cause App will receive `OnHMIStatus` RPC before receiving `RegisterAppInterfaceResponse` RPC, it is incorrect communication sequence.

**Comment by zhouxin627** [comment]
Hi @LuxoftAKutsan, do you have a plan of making a PR to fix this issue.

**Comment by zhouxin627** [comment]
Hi @LuxoftAKutsan, I'm sorry to disturb you. This issue is a top priority for us. Could you please confirm the comment we answered, and give some more comments or suggestions. Thank you very much.

**Comment by Shohei-Kawano** [comment]
@LuxoftAKutsan -san,
My team member zhouxin627 has answered your comment, when will you be able to respond?

@theresalech -san,
This ticket has been delayed. Sorry to trouble you, but can you support LuxoftAKutsan -san and us?

**Comment by theresalech** [comment]
@Shohei-Kawano, Livio was not made aware that this PR was ready for review. As reported to the Steering Committee, we have completed development for Core 7.0 and are currently testing and preparing the Release Candidate for Steering Committee review. If time allows before Release Candidate delivery, we will look to include this PR as well.

**Comment by JackLivio** [comment]
I think the simpler fix would be to add a case to usage statistics for hmi level `INVALID_ENUM`. `INVALID_ENUM` is used in the window resumption logic so it does not mean invalid level, it means the level has not been assigned as the app is still registering.

```
void UsageStatistics::RecordHmiStateChanged(HMILevel::eType new_hmi_level) {
  using namespace mobile_apis::HMILevel;
  AppStopwatchId next_stopwatch = SECONDS_HMI_NONE;
  switch (new_hmi_level) {
    case HMI_FULL:
      next_stopwatch = SECONDS_HMI_FULL;
      break;
    case HMI_LIMITED:
      next_stopwatch = SECONDS_HMI_LIMITED;
      break;
    case HMI_BACKGROUND:
      next_stopwatch = SECONDS_HMI_BACKGROUND;
      break;
    case HMI_NONE:
      next_stopwatch = SECONDS_HMI_NONE;
      break;
    case INVALID_ENUM:
      // App still registering
      break;
    default:
      NOTREACHED();
  }
  time_in_hmi_state_sptr_->Switch(next_stopwatch);
}
```

I think this would prevent your crash in this case.

**Comment by theresalech** [comment]
@zhouxin627, please see the Project Maintainer's suggestion above for this PR and let us know your thoughts. Thank you!

**Comment by Shohei-Kawano** [comment]
@theresalech -san.
Thank you for the announcement.

@JackLivio -san, 
Thank you for modifying the this issue. We will check how to fix it and comment if there is anything.

**Comment by Shohei-Kawano** [comment]
@JackLivio -san.
From Nexty's engineer member.
====
This pullrequest has add a new defination value of HMI_LEVEL as INVALID_ENUM.
It could fixed issue2808,but the default defination miss is not the root cause of this crash.
The root cause is the application register sequence:
 1.Add app to applist
 2.Initialize App HMILevel
in this sequence,it still cause wrong status of HMI_LEVEL for sometime.
For example,HMI sends a OnEventChanged(DEACTIVATE_HMI) event to SDLCore when the HMILevel is INVALID_ENUM,
which will cause HMILevel value change to BACKGROUND from INVALID_ENUM, as result, SDLCore will send OnHmiStatus(BACKGROUND) to mobileApp.
====

**Comment by JackLivio** [comment]
@Shohei-Kawano Thank you for the update. hmi_state.cc had some refactoring this release so i attempted to resolve the merge conflicts this pr was encountering: https://github.com/smartdevicelink/sdl_core/pull/3546/files

I think I applied the same logic, but a review would be appreciated.

**Comment by JackLivio** [comment]
@Shohei-Kawano @zhouxin627 

Please find updated version of this pr here: https://github.com/smartdevicelink/sdl_core/pull/3546

**Comment by JackLivio** [comment]
Closing in favor off #3546

**Pull request closed without merging**
