### PR TITLE
Return back deleted UT

### PR DESCRIPTION
**Pull request by LevchenkoS**
Returned back unit-tests deleted in PR #773

Related to: [APPLINK-27350](https://adc.luxoft.com/jira/browse/APPLINK-27350)

@okozlovlux, @LuxoftAKutsan, @vlantonov, @VVeremjova , @pvvasilev, @AByzhynar, please review.

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by okozlovlux** [comment]
@LevchenkoS , reviewed

**Comment by vlantonov** [comment]
@LevchenkoS Reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@LevchenkoS Reviewed

**Comment by LevchenkoS** [comment]
@pvvasilev, please, review this pull request. Only you was left.

**Comment by pvvasilev** [comment]
@LevchenkoS Reviewed.

**Pull request merged**
