### PR TITLE
Move interface classes to correct directory

### PR DESCRIPTION
**Pull request by Kozoriz**
- Interfaces that used in several components moved to src/components/include/<component_name>
- Mocks of this interfaces moved to src/components/include/test/<component_name>
- All header-guards updated

### CODE REVIEW

**Comment by Kozoriz** [comment]
Please review : @anosach-luxoft , @AByzhynar , @okozlovlux, @LevchenkoS, @dev-gh , @VProdanov

**Comment by LevchenkoS** [comment]
@Kozoriz Reviewed

**Comment by okozlovlux** [comment]
@Kozoriz reviewed

**Comment by AByzhynar** [comment]
@Kozoriz All header guards in move files are wrong. Every PR must be buildable and correct. If you change location or name of some file - you have to change appropriate header guards for these files. Not in separate task. Don't put regression into code. It was right before - you changed something - now it bacame bad and you are going to fix in separate task. It's wrong concept.

**Comment by Kozoriz** [comment]
@AByzhynar , all header-guards was corrected in c086c9e

**Comment by AByzhynar** [comment]
Reviewed

**Comment by dev-gh** [comment]
Visually reviewed

**Comment by VProdanov** [comment]
@Kozoriz Reviewed

**Pull request merged**
