### PR TITLE
Refactor build scripts

### PR DESCRIPTION
**Pull request by anosach-luxoft**
PR provides following changes:
* Move all windows-specific build scripts to `tools\ms` directory
* Reduce build scripts amount by collecting logic to few `.cmd` files
* Reduce environment variables amount by using local variables in `.cmd` files
* Make environment variables names consistent (add `SDL_` prefix)
* Remove legacy files from repository
* Correct information regarding `sqlite3` lib in `README` file

Related-issue: [APPLINK-25311](https://adc.luxoft.com/jira/browse/APPLINK-25311)

@LuxoftAKutsan, @dev-gh, @LevchenkoS, @Kozoriz, @nk0leg, @AByzhynar  please review

### CODE REVIEW

**Comment by anosach-luxoft** [comment]
@LuxoftAKutsan, @dev-gh, @LevchenkoS, @Kozoriz, @nk0leg, @AByzhynar please review

**Comment by LevchenkoS** [comment]
@anosach-luxoft, reviewed.

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by nk0leg** [comment]
Reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Comment by AByzhynar** [comment]
@anosach-luxoft Please let me know before merge to make appropriate changes on CI server.

**Comment by Kozoriz** [comment]
Reviewed

**Comment by dev-gh** [comment]
Reviewed

**Pull request merged**
