### PR TITLE
fix: reduce logs during streaming

### PR DESCRIPTION
**Pull request by shoamano83**
Fixes https://github.com/smartdevicelink/sdl_core/issues/1777.

I thought that removing particular logs completely will confuse developers and hence it will be a bad idea. So instead of eliminating logs, log levels are decreased.
Head unit systems with video streaming feature can set log output level to DEBUG (or higher) to get rid of the logs.

### CODE REVIEW

**Comment by shoamano83** [comment]
@JackLivio @jacobkeeler Please kindly review.

**Comment by JackLivio** [comment]
@shoamano83 I like this change. Could you please retarget for the 4.4.0 release candidate branch? I would like to put this into the next release since most of the new features revolve around video streaming.

**Comment by JackLivio** [comment]
@shoamano83 We are still discussing if these logs are needed at all, or if trace is the best log level for these logs.

**Comment by shoamano83** [comment]
Thanks for your comment. Let me know if you want to remove some of the logs, I will update PR accordingly.

**Review by jacobkeeler — APPROVED** [review]

**Pull request merged**
