### PR TITLE
Avoid processing streaming data packets after streaming stopping

### LINKED ISSUE #3811: Core sometimes sends redundant OnAudioDataStreaming(true/false) notifications
### Bug Report
Core sometimes sends redundant `OnAudioDataStreaming(true/false)` notifications to HMI

##### Occurrences
Rare (~0.1%)

##### Reproduction Steps
1. App starts Video and Audio streaming at the same time
2. Core sends requests to HMI:
a) `Navigation.StartStream`
b) `Navigation.StartAudioStream`
3. HMI responds to a) and doesn't respond to b)
4. Core sends 3 more b) requests
5. HMI still doesn't respond

##### Expected Behavior
Core does:
- stop Audio service
- not stop Video service
- continue Video streaming from App
- not unregister App with `PROTOCOL_VIOLATION` reason
- not send redundant `Navi.OnAudioDataStreaming` messages to HMI

##### Observed Behavior
Core does:
- send redundant Navi.OnAudioDataStreaming messages to HMI

##### OS & Version Information
* OS/Version: Ubuntu 20.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (31324d5)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
- Impacted scripts:
    - https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/8_0/3479_1_Audio-Video_streaming_same_time_no_response_from_HMI_for_Audio.lua
    - https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/8_0/3479_2_Audio-Video_streaming_same_time_no_response_from_HMI_for_Video.lua
- Report and Logs:
    - [3811_Audio.zip](https://github.com/smartdevicelink/sdl_core/files/7470545/3811_Audio.zip)
    - [3811_Video.zip](https://github.com/smartdevicelink/sdl_core/files/7470546/3811_Video.zip)

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #3811 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF test scripts

### Summary
In some situations streaming data packets may be received during streaming stopping. In this case processing of such packet will be performed right after completion of streaming stopping process due to `streaming_stop_lock_`. So in this case we need to skip processing of such packet, that's why new flags `video_streaming_stopped_` and `audio_streaming_stopped_` are added for both services. Also outdated comments are removed with locks, which now are redundant due to presence of `streaming_stop_lock_`.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ychernysheva** [comment]
@theresalech this PR is ready for Livio review

**Review by iCollin — COMMENTED** [review]
I am seeing some ATF tests failing with this PR, do you see these failing as well? Am I missing a related ATF PR?

```
./test_scripts/Defects/8_0/3479_3_Audio-Video_streaming_delayed_no_response_from_HMI_for_Audio.lua
./test_scripts/Defects/8_0/3479_4_Audio-Video_streaming_delayed_no_response_from_HMI_for_Video.lua
./test_scripts/Defects/8_0/3479_2_Audio-Video_streaming_same_time_no_response_from_HMI_for_Video.lua
./test_scripts/Defects/8_0/3479_1_Audio-Video_streaming_same_time_no_response_from_HMI_for_Audio.lua
./test_scripts/MobileProjection/Phase2/smoke/019_SDL_audio_source_during_audio_video.lua
./test_scripts/MobileProjection/Phase2/019_SDL_audio_source_during_audio_video.lua
```

EDIT: passing now

**Comment by LitvinenkoIra** [comment]
@iCollin We are doing regression testing right now, I’ll let you know when this PR is ready for re-review

**Comment by GetmanetsIrina** [comment]
@iCollin Looks like scripts have been failed because of not corresponding script version.
I had the same issue, but with the latest version of scripts ([167bdd1](https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop)) I have PASS status.

PR is ready for review.

**Comment by iCollin** [comment]
Thank you, yes I see all test passing now. [This comment](https://github.com/smartdevicelink/sdl_core/pull/3816#discussion_r783119072) is still applicable, and after that this should be good to merge.

**Pull request merged**
