### PR TITLE
hotfix/Fix_UT_for_Protocol_handler_in_genivi

### PR DESCRIPTION
**Pull request by monstersem**
Enabled 5 unit tests.

Related:
        APPLINK-19076

### CODE REVIEW

**Comment by monstersem** [comment]
Please review: @AGaliuzov , @VVeremjova, @iAndrew5 , @Kozoriz

**Comment by iAndrew5** [comment]
Reviewed

**Comment by Kozoriz** [comment]
reviewed

**Comment by VVeremjova** [comment]
Reviewed

**Pull request merged**
