### PR TITLE
Fix issue when SDL responds with GENERIC_ERROR on RPC request

### PR DESCRIPTION
**Pull request by okozlovlux**
- added checking consent groups in access_remote_impl

### CODE REVIEW

**Comment by okozlovlux** [comment]
@LuxoftAKutsan @pold500 @istoilovgithub @indlu please review

**Comment by okozlovlux** [comment]
Rebuild required

**Comment by okozlovlux** [comment]
@istoilovgithub , `Nice catch!` ? What do you mean?

**Comment by istoilovgithub** [comment]
@okozlovlux I means that you did a great job!

**Comment by okozlovlux** [comment]
@LuxoftAKutsan @pold500 @istoilovgithub @indlu please review again

**Comment by okozlovlux** [comment]
Rebuild required

**Comment by okozlovlux** [comment]
@pold500 @istoilovgithub  gentle remind

**Pull request merged**
