### PR TITLE
Mismatch for mandatory parameter between MOBILE_API and HMI_API.

### LINKED ISSUE #1846: Mismatch for mandatory parameter between MOBILE_API and HMI_API
There is a  mismatch for the mandatory parameter between the MOBILE_API and the HMI_API for the following parameters:

- distanceToManeuver
- distanceToManeuverScale

The MOBILE_API is reflecting that these parameters are not mandatory, whereas the HMI_API reflects that they are mandatory.

### PR DESCRIPTION
**Pull request by ONyzhnyk-Luxoft**
Fixes #1846
https://github.com/SmartDeviceLink/sdl_core/issues/1846

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Summary
Mandatory parameter in distanceToManeuver and distanceToManeuver changed in accordance with the same on MOBILE_API.xml.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@robinmk, please, approve alignment of MOBILE_API and HMI_API introduced in this fix.

**Comment by robinmk** [comment]
@KhrystynaDubovyk , wouldn't this be a breaking change for the Open?
I will like to discuss this with the team that triaged the bug to understand if this was already accepted.

CC:
@mrapitis , @stefanek22 , @yang1070

**Comment by jacobkeeler** [comment]
@robinmk yes, this would be a breaking change. A proposal would be needed to make this sort of change

**Comment by KhrystynaDubovyk** [comment]
@jacobkeeler, I believe, the issue, and this PR could be closed. 
[The proposal SDL-0285](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0285-ConstantTBT-Update.md#proposed-solution) is created and accepted.

**Comment by jacobkeeler** [comment]
Closing, proposal for change has been accepted, but this change must be moved to the rpc_spec repo. Associated issue: https://github.com/smartdevicelink/rpc_spec/issues/227

**Pull request closed without merging**
