### PR TITLE
Remove legacy  _EXT and INFO macro

### PR DESCRIPTION
**Pull request by pestOO**
Removed unused _EXT macro definition
Moved logger macro in alphabetical order
Removed legacy _EXT macro usage
Replaced INFO macros to TRACE and debug
Removed symlinks

Implements: APPLINK-15680

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@pestOO , please do rebase the PR since it is not mergable

**Comment by pestOO** [comment]
@AGaliuzov, rebased.

Waht about not hot, but common fixes like that? =)

**Comment by AGaliuzov** [comment]
@pestOO ,
According to the gitflow any bug fix branch should start from `hotfix/` prefix.

In common such naming policy uses for hotfixes into master or release branch.
But in order to be uniform we use such naming policy for develop either

**Comment by justinjdickow** [comment]
@pestOO 
Aleks is correct. If a branch adds a feature it has the `feature/` prefix for the branch name. If a branch fixes a bug is has the `hotfix/` prefix. These are generally committed to release branches (such as release/4.0.0 or master) but may also be applied to pull requests into `develop` when a feature was considered complete but a bug is found after the merge.

**Comment by justinjdickow** [comment]
Basically the only time that a `hotfix/` branch is merged into develop is if it fixes a bug for a feature that exists in develop but doesn't exist in a release or the master branch (so a fix for a new feature).

**Pull request merged**
