### PR TITLE
Resolve am test linker dependencies

### PR DESCRIPTION
**Pull request by anosach-luxoft**
@LuxoftAKutsan, @dev-gh, @LevchenkoS, @Kozoriz please review

### CODE REVIEW

**Comment by LevchenkoS** [comment]
@anosach-luxoft, reviewed.

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by dev-gh** [comment]
Reviewed

**Pull request merged**
