### PR TITLE
change application accessor list from iterator to const iterator

### PR DESCRIPTION
**Pull request by BrandonHe**
Just a small update to iterate ApplicationListAccessor from iterator to const_iterator to prevent *it from changing.
Please review@AGaliuzov @justinjdickow

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@BrandonHe, have you tried to run the unit test for your changes?

**Comment by BrandonHe** [comment]
@AGaliuzov Yes, I have built with BUILD_TEST ON and also have a local test, both of them success.

**Comment by AGaliuzov** [comment]
@BrandonHe could you please rebase this branch, so I will be able to merge it

**Comment by BrandonHe** [comment]
@AGaliuzov 

Rebased this branch, could you please review it?

**Comment by AGaliuzov** [comment]
@BrandonHe 
I'm not sure if you rebasing is proper one since now the pull request has a lot of commit which is quite starnge. Could you review your changes one more time an leave only your own commits

**Comment by AGaliuzov** [comment]
@justinjdickow it seems like system time has been broken.

**Comment by AGaliuzov** [comment]
@BrandonHe, could you please remove the commits which not belong to you from this pull request?

**Comment by BrandonHe** [comment]
@AGaliuzov 
That is also confused me, I don't know what caused this ridiculous info that commit on May 2016. I just rebased again, looks now is correct. Could you please review again?

**Comment by BrandonHe** [comment]
Hi @AGaliuzov @justinjdickow 
All changes in this pull request are based on component of "application manager", I cloned develop branch and ran test, Application_manager_test passed. But utils_test was timeout.
```
brandon@brandon-VirtualBox:~/github/build_for_pull_request$ make test
Running tests...
Test project /home/brandon/github/build_for_pull_request
      Start  1: test_JSONCPP
 1/20 Test  #1: test_JSONCPP ......................   Passed    0.05 sec
      Start  2: test_generated_interface
 2/20 Test  #2: test_generated_interface ..........   Passed    0.02 sec
      Start  3: transport_manager_test
 3/20 Test  #3: transport_manager_test ............   Passed    0.24 sec
      Start  4: resumption_test
 4/20 Test  #4: resumption_test ...................   Passed    0.02 sec
      Start  5: formatters_test
 5/20 Test  #5: formatters_test ...................   Passed    0.22 sec
      Start  6: protocol_handler_test
 6/20 Test  #6: protocol_handler_test .............   Passed   10.84 sec
      Start  7: connection_handler_test
 7/20 Test  #7: connection_handler_test ...........   Passed   83.39 sec
      Start  8: utils_test
 8/20 Test  #8: utils_test ........................***Timeout 1500.01 sec
      Start  9: security_manager_test
 9/20 Test  #9: security_manager_test .............   Passed   10.48 sec
      Start 10: policy_test
10/20 Test #10: policy_test .......................   Passed    5.20 sec
      Start 11: rpc_base_test
11/20 Test #11: rpc_base_test .....................   Passed    0.02 sec
      Start 12: smart_object_test
12/20 Test #12: smart_object_test .................   Passed    1.72 sec
      Start 13: application_manager_test
13/20 Test #13: application_manager_test ..........   Passed    0.43 sec
      Start 14: resumption/data_resumption_test
14/20 Test #14: resumption/data_resumption_test ...   Passed    0.01 sec
      Start 15: state_controller_test
15/20 Test #15: state_controller_test .............   Passed    0.24 sec
      Start 16: message_helper_test
16/20 Test #16: message_helper_test ...............   Passed    0.01 sec
      Start 17: hmi_message_handler_test
17/20 Test #17: hmi_message_handler_test ..........   Passed    0.01 sec
      Start 18: config_profile_test
18/20 Test #18: config_profile_test ...............   Passed    0.30 sec
      Start 19: media_manager_test
19/20 Test #19: media_manager_test ................   Passed    0.06 sec
      Start 20: telemetry_monitor_test
20/20 Test #20: telemetry_monitor_test ............   Passed    0.02 sec

95% tests passed, 1 tests failed out of 20

Total Test time (real) = 1613.36 sec

The following tests FAILED:
	  8 - utils_test (Timeout)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by AGaliuzov** [comment]
@BrandonHe I have checkout your branch and run test on my machine and all of them  are green. So no any timeouts or failed test.. Our internal build server is also ok.

I think I will merge this PR and in case we will find any issue in the feature they are will be fixed within separate PR

**Pull request merged**
