### PR TITLE
Hotfix/sdl crashes during start if preloaded pt file is absent

### PR DESCRIPTION
**Pull request by AGritsevich**
Please review @pestOO , @anosach-luxoft , @malirod.

### CODE REVIEW

**Comment by malirod** [comment]
Reviewed

**Comment by AGritsevich** [comment]
@anosach-luxoft  see 05a70d837c03560eb3af5d56155d8d334ffc1b62

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by pestOO** [comment]
Have you tested Srat/Stop with an ATF, Lowvoltage manualy?

**Comment by AGritsevich** [comment]
@pestOO , in Genevi have no Lowvoltage.

**Comment by pestOO** [comment]
@AGritsevich but we have a `StartComponents` and `Stop`.
I think we need to cover it.

**Comment by pestOO** [comment]
Reviewed

**Pull request merged**
