### PR TITLE
EndServiceAck processing

### PR DESCRIPTION
**Pull request by Anatoliy-Leshin**
Process EndServiceAck from mobile;
    
Add EndServiceAck message processing on protocol_handler level.
PH notify connection_handler, CH notify application_manager.
On AM level SDL turns off video/audio service for application.

### CODE REVIEW

**Comment by Anatoliy-Leshin** [comment]
Please review @pestOO  @AByzhynar @anosach-luxoft 

This is same code for Genivi from https://github.com/CustomSDL/sdl_panasonic/pull/134

**Comment by pestOO** [comment]
Reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Comment by Anatoliy-Leshin** [comment]
@anosach-luxoft PR can be merged

**Comment by AGaliuzov** [comment]
@Anatoliy-Leshin are you going to modify this PR?

**Comment by Anatoliy-Leshin** [comment]
@AGaliuzov, check this out

**Pull request merged**
