### PR TITLE
Extract common interfaces

### PR DESCRIPTION
**Pull request by istoilovgithub**
Structure changes - extracting common interfaces to global include folder

Related tasks [APPLINK-30588](https://adc.luxoft.com/jira/browse/APPLINK-30588) [APPLINK-30974](https://adc.luxoft.com/jira/browse/APPLINK-30974)

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@istoilovgithub please check CI issues

**Comment by istoilovgithub** [comment]
@LuxoftAKutsan  I've checked out the issues, but I am unable to reproducible them locally even with docker. Any idea how trigger a new build without code changes?

**Comment by LuxoftAKutsan** [comment]
Rebuild required

**Comment by LuxoftAKutsan** [comment]
@istoilovgithub you can write "Rebuild required" as comment.

**Comment by AByzhynar** [comment]
@istoilovgithub Please exclude me from this code review

**Comment by istoilovgithub** [comment]
@LuxoftAKutsan Fixed build with 30f1903

**Pull request merged**
