### PR TITLE
Fix build issues with TransportManager UT

### PR DESCRIPTION
**Pull request by istoilovgithub**
Related tasks [APPLINK-30588](https://adc.luxoft.com/jira/browse/APPLINK-30588) [APPLINK-30977](https://adc.luxoft.com/jira/browse/APPLINK-30977)

### CODE REVIEW

**Comment by istoilovgithub** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
@istoilovgithub I think you also should delete
 EXPECT_CALL(*tm_listener_, OnDeviceListUpdated(vector_dev_info))  in TransportManagerImplTest.ReceiveEventFromDevice_DeviceListUpdated, because build is still failed.

**Comment by istoilovgithub** [comment]
@LitvinenkoIra fixed in a29765a

**Comment by istoilovgithub** [comment]
Rebuild required

**Comment by istoilovgithub** [comment]
Rebuild required

**Pull request merged**
