### PR TITLE
Fix core crash: assert to double taking mutex

### PR DESCRIPTION
**Pull request by AGritsevich**
SDL crashed when trying got mutex in sub method. Change normal mutex to recursive to fix this problem.
Fixes: [APPLINK-19317](https://adc.luxoft.com/jira/browse/APPLINK-19317)

### CODE REVIEW

**Comment by AGritsevich** [comment]
Please review: @pestOO , @AGaliuzov

**Comment by pestOO** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
The usage of recursive mutex looks like workaround. Do you now a really reason why SDL lock this mutex twice? Maybe better to fix this instead of masking problem with recursive mutex

**Comment by anosach-luxoft** [comment]
+1 to remove recursive mutex

**Comment by AGritsevich** [comment]
Anyway it's way cheap and fast.

**Comment by AGritsevich** [comment]
Ok, I'll try to find real problem. Thank you for opinion.

**Comment by AGritsevich** [comment]
I removed recursive mutex and just make minimal scope for automutex. I hope you'll like it!
Please review @pestOO, @AGaliuzov, @anosach-luxoft.

**Comment by anosach-luxoft** [comment]
:+1:

**Comment by AGritsevich** [comment]
@anosach-luxoft, I don't think so.

**Comment by anosach-luxoft** [comment]
@AGritsevich, you shouldn't think about it :smile: You have to be sure.

**Comment by AGritsevich** [comment]
I'm sure.

**Pull request merged**
