### PR TITLE
Hotfix/implement and fixed unit tests for policy

### PR DESCRIPTION
**Pull request by OHerasym**
Changed branch name.

### CODE REVIEW

**Comment by monstersem** [comment]
Please rewiew: @AGaliuzov

**Comment by AGaliuzov** [comment]
@monstersem , please sqush the commits and rebase them

**Comment by monstersem** [comment]
@AGaliuzov , Done

**Comment by anosach-luxoft** [comment]
@OHerasym, please rebase

**Comment by OHerasym** [comment]
@anosach-luxoft , Done

**Pull request merged**
