### PR TITLE
SendLocation updates feature

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
SDL implementation of SendLocation updates feature

Proposal: [SendLocation Updates](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0004-sendlocation-updates.md)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
Rebuild required

**Comment by AKalinich-Luxoft** [comment]
Rebased after merge conflicts

**Comment by LitvinenkoIra** [comment]
Rebased after merge conflicts

**Comment by jacobkeeler** [comment]
Already implemented, closing

**Pull request closed without merging**
