### PR TITLE
Replace bool with enum TimerType value in timer start

### PR DESCRIPTION
**Pull request by vlantonov**
Enum type created in the Timer header.
Timer types defined: Single Shot and Periodic
Corresponding boolean values are replaced with enum type values.

### CODE REVIEW

**Comment by vlantonov** [comment]
Please review: @AByzhynar , @AGaliuzov , @anosach-luxoft , @VProdanov

**Comment by AByzhynar** [comment]
Reviewed

**Comment by VProdanov** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by vlantonov** [comment]
Please review @LuxoftAKutsan @malirod The build has passed OK, but there are problems with codecov which prevent me from merging this branch.

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
@vlantonov @malirod code cov is just tell us that  changed lines are not covered by UT. You is free to merge this branch

**Comment by vlantonov** [comment]
@LuxoftAKutsan Thank you for the review. Unfortunately I do not have the rights to merge in case errors as abovementioned are present, so I would ask you or @malirod to merge this pull request when review is completed.

**Pull request merged**
