### PR TITLE
Fix V5 protocol message bson params

### LINKED ISSUE #2142: V5 Protocol Messages do not encrypt payload of Control Frame Message Types
### Bug Report
Failure occurs when attempting to use a protected video or audio service with sdl core when using a max protocol version of 5 in the SmartDeviceLink.ini file.  This is because control frame message message types are being sent by sdl core with an encryption flag set to true, however the payload data is not encrypted causing failures when attempting to decrypt the payload data.  Downgrading to version 4 of the protocol by setting the max value to 4 works around the problem.

##### Reproduction Steps
1. Attempt to start a protected service with sdl core such as video or audio
2. Take note of the unencrypted payload data that is sent to the mobile when control frames are being used.
3. Take note that the protected service is not successfully established

##### Expected Behavior
When the encryption flag is set to true in a protocol message, the payload of the message is properly encrypted.

##### Observed Behavior
Unencrypted payload data for control frame type protocol messages even though the encryption bit is set to true in the message header.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 4.5, 4.4
* Testing Against: VM running sdl with webHMI

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #2142 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by unit tests
ATF scripts

### Summary
There was a problem with V5 control frames encryption/decryption related to the wrong conditions in encrypt/decrypt functions in protocol manager. Also there was a problem with allocated bson params object passed as a pointer to another place.

NOTE
This fix should be merged after #2105 and #2068 features as it contains commit history from these branches. Please review only the last commit from this PR.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by mrapitis** [comment]
@theresalech this PR is ready for review.

**Comment by JackLivio** [comment]
@AKalinich-Luxoft There are a lot of merge conflicts now that getSystemTime has been merged. Can you rebase this PR on the current develop?

**Comment by JackLivio** [comment]
Also PR has 38 unit test failures in security_manager_test

**Comment by AKalinich-Luxoft** [comment]
@JackLivio conflicts has been resolved. You just need to merge #2217 and #2218 first.

**Pull request merged**
