### PR TITLE
SDL doesn't crash with Core dump caused by double free on app exit

### PR DESCRIPTION
**Pull request by okoreniak**
Iterator increment operator was missed in map erase operation.
Related to: APPLINK-18922

@AGritsevich @Anatoliy-Leshin @anosach-luxoft @VProdanov  @VVeremjova : please review.

### CODE REVIEW

**Comment by AGritsevich** [comment]
Reviewed.

**Comment by VProdanov** [comment]
Its good to use imperative mood in the subject line of the commit.
https://adc.luxoft.com/confluence/display/APPLINK/Commit+in+git+-+the+best+practices
Reviewed.

**Comment by VVeremjova** [comment]
Reviewed

**Comment by Anatoliy-Leshin** [comment]
Reviewed

**Pull request merged**
