### PR TITLE
Fix/fix u bin auto trace test

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Rework AutoTrace test,
Figured out rather big problem in message queue disable test until APPLINK-24336 wont be resolved
Old pull request was closed by mistake #552

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@malirod @okozlov please review
Oll other reviewedrs already reviewed in #552

**Comment by okozlovlux** [comment]
@LuxoftAKutsan reviewed

**Comment by malirod** [comment]
reviewed

**Comment by LuxoftAKutsan** [comment]
@AGritsevich  please merge this pull reqest

**Pull request merged**
