### PR TITLE
Adds sending of SDL and SW versions within RAI.

### PR DESCRIPTION
**Pull request by dev-gh**
SDL will send request to get SW version from vehichle and also will
provide SDL and SW version within RAI response for each application.

Implements: APPLINK-11284

### CODE REVIEW

**Comment by justinjdickow** [comment]
@stefanek22 I believe we want SDL and system sw version in 4.0.0, correct?

**Comment by stefanek22** [comment]
Yes, that is the expectation.

**Comment by justinjdickow** [comment]
@dev-gh Can you close this PR and submit as a hotfix into the release/4.0.0 branch? It should be merged into develop afterwards.

**Comment by dev-gh** [comment]
@justinjdickow This PR is an addition to another PR #131, which is merged to develop already.
So we have to send both these PRs to release/4.0.0. Is it ok for you?

**Comment by AGaliuzov** [comment]
@dev-gh , yes please send PR for all neccessary functionality in release branch as a hotfix

**Comment by dev-gh** [comment]
Sent within #204 to release/4.0.0

**Pull request closed without merging**
