### PR TITLE
Cover application state

### PR DESCRIPTION
**Pull request by VVeremjova**
Please review @okozlovlux,  @dtrunov, @LevchenkoS
Related to [APPLINK-23479](https://adc.luxoft.com/jira/browse/APPLINK-23479)

### CODE REVIEW

**Comment by okozlovlux** [comment]
@VVeremjova reviewed

**Comment by LevchenkoS** [comment]
@VVeremjova Reviewed.

**Comment by dtrunov** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
@VVeremjova branch name does not match repository agreement

**Pull request closed without merging**
