### PR TITLE
Remove SAD source

### PR DESCRIPTION
**Pull request by pestOO**
SAD is now available on the Ford developers portal:
https://smartdevicelink.com/en/guides/core/software-architecture-document/table-of-contents/
The source files are available in the guides repository:
https://github.com/smartdevicelink/sdl_core_guides/pull/4

Related issues: [APPLINK-26096](https://adc.luxoft.com/jira/browse/APPLINK-26096), [APPLINK-26666](https://adc.luxoft.com/jira/browse/APPLINK-26666)

### CODE REVIEW

**Comment by pestOO** [comment]
@LuxoftAKutsan, @anosach-luxoft, please review

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
Reviewed

**Comment by pestOO** [comment]
@anosach-luxoft, please merge

**Pull request merged**
