### PR TITLE
Fixes dump on SDL.ActivateApp call

### PR DESCRIPTION
**Pull request by dev-gh**
Relates-to: APPLINK-25446

### CODE REVIEW

**Comment by dev-gh** [comment]
@VProdanov @OHerasym @AByzhynar @anosach-luxoft @AGaliuzov 
Please review

**Comment by AByzhynar** [comment]
@dev-gh Please rebase and use `tools/infrastructure/check_style.sh --fix`. Run it from source directory.

**Comment by dev-gh** [comment]
@AByzhynar 
To what branch do I have to rebase? Now I'm not getting any error event with --fix

**Comment by AByzhynar** [comment]
@dev-gh Sorry for wrong info. No branch to rebase exists as the code in release/4.1.0 is not formatted yet.

**Comment by AByzhynar** [comment]
Reviewed

**Comment by VProdanov** [comment]
Reviewed

**Comment by OHerasym** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
Reviewed

**Pull request merged**
