### PR TITLE
Update logger properties to log to file only

### PR DESCRIPTION
**Pull request by orhan-mehmedov**
Leave only logging to file in log4cxx.properties
due to slow printing to console/terminal.
Workaround for APPLINK-17599.

Related to [APPLINK-17599](https://adc.luxoft.com/jira/browse/APPLINK-17599).

### CODE REVIEW

**Comment by orhan-mehmedov** [comment]
Please review,
@AByzhynar @LuxoftAKutsan @anosach-luxoft @dev-gh @Kozoriz @wolfylambova22 @pvvasilev

**Comment by LuxoftAKutsan** [comment]
@AGritsevich  Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by dev-gh** [comment]
Reviewed

**Comment by pvvasilev** [comment]
@orhan-mehmedov Reviewed.

**Comment by wolfylambova22** [comment]
@orhan-mehmedov Reviewed.

**Comment by pestOO** [comment]
@orhan-mehmedov,
Please, clarify logging requirements with customer.
I see a risk of *"unexpected silence"* SDL working.

Also, please, add using `tail -f` in one of the readme files

**Comment by orhan-mehmedov** [comment]
@pestOO, it was clarified with our TL. According him no need to clarify this change with the client.
Which readme file to update? I do not see suitable one.

**Comment by pestOO** [comment]
@orhan-mehmedov, 
Ok.

**Comment by AByzhynar** [comment]
Reviewed

**Pull request merged**
