### PR TITLE
fix: invalid memory access in websocket_handler

### PR DESCRIPTION
**Pull request by shoamano83**
This is to fix https://github.com/smartdevicelink/sdl_core/issues/1686. Using the value of 'size' seems wrong, it should be 'length'.
Note: an unit test for this fix is not available since invalid memory access cannot be detected with an unit test.

### CODE REVIEW

**Comment by shoamano83** [comment]
@JackLivio Please kindly review.

**Comment by shoamano83** [comment]
The fix was incomplete and needs some more work.

**Comment by shoamano83** [comment]
This is **ready for review** now.

**Comment by JackLivio** [comment]
@shoamano83 verified fix removes issue from valgrind

**Pull request merged**
