### PR TITLE
Fix wrong success code for ReadDID request truncated data

### LINKED ISSUE #1399: CCB: Fix wrong success code for ReadDID request truncated data
### Bug Report
SDL returns mobile CANCEL_ROUTE with success: false if it received TRUNCATED_DATA from HMI

##### Reproduction Steps
- Start SDL and HMI
- Connect mobile and create mobile session
- Register mobile App
- Activate mobile App
- Perform PTU sequence
- Send RPC "ReadDID" from mobile App 
- Send response on request "VehicleInfo.ReadDID" from HMI with resultCode = "TRUNCATED_DATA"

##### Expected Behavior
SDL sends TRUNCATED_DATA with success: true to mobile

##### Observed Behavior
SDL sends TRUNCATED_DATA with success: false to mobile

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: 65ade78808a37560c1a55de058201a10296f14d1
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
Script: [ATF_ReadDID_TRUNCATED_DATA.tar.gz](https://github.com/smartdevicelink/sdl_core/files/857446/ATF_ReadDID_TRUNCATED_DATA.tar.gz)

### PR DESCRIPTION
**Pull request by Ypostolov**
Fixes #1399 

This PR is **ready** ready for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Provide ATF tests

### Summary
Fixed SDL sends TRUNCATED_DATA with success: true to mobile

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by vkushnirenko-luxoft** [comment]
Rebuild required

**Comment by dboltovskyi** [comment]
Rebuild required

**Comment by LitvinenkoIra** [comment]
Rebased to the latest develop (e137556)

**Comment by IGapchuk** [comment]
Rebase on the lates develop (49c29364460faa527bc758d0fd6b108463f8d82d)

**Comment by iCollin** [comment]
@Ypostolov 
Hello, changes look good but lets keep mobile and HMI consistent.

Can you add `mobile_apis::Result::TRUNCATED_DATA` as a success result in `CommandRequestImpl::IsMobileResultSuccess` right above your existing changes?

**Comment by Ypostolov** [comment]
@iCollin 
Thanks for the suggestion!
'mobile_apis::Result::TRUNCATED_DATA' added, please take a look 67a6669d789fba9b3002074b68ac78b7b2106fc9

**Pull request merged**
