### PR TITLE
Feature/expand put file

### LINKED ISSUE #1455: [SDL 0037] Expand Mobile putfile RPC
Proposal: [Expand Mobile putfile RPC](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0037-Expand-Mobile-putfile-RPC.md)

> This proposal seeks to enhance the reliability of large data transfers to the head unit by introducing a field for CRC in the `putFile` RPC.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/123

Steering Committee Decision:

> The Steering Committee has agreed to accept this proposal, given the revisions to add clarity and address initial concerns (outlined [here](https://github.com/smartdevicelink/sdl_evolution/commit/4b42ec004dfffb9160c3985cc3487c93bfcc8379)).

### PR DESCRIPTION
**Pull request by AByzhynar**
Fixes #1455 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Unit tests are provided
ATF tests scripts are provided here: [feature/expand_put_file](https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/feature/expand_put_file)

### Summary
Implemented function in PutFile which correctly calculates CRC32 checksum
Added comparison of calculated CRC checksum with received in PutFile
request.
Added PutFile response generation in case of CRC sum mismatch
Fixed handling  of unsigned integer values

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by BSolonenko** [comment]
Rebuild required

**Comment by mrapitis** [comment]
We are seeing issues with putFile when attempting to include a crc32 parameter in a single putfile.  

Response from core when sending a putfile via mobile with the crc32 parameter is included:
```
DEBUG [23 Apr 2018 09:43:10,558][0x7f04c0ff9700][ApplicationManager] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/mobile_message_handler.cc:122 RawMessage* application_manager::MobileMessageHandler::HandleOutgoingMessageProtocol: Outgoing RPC_INFO: 1, Response, 32, 104, {
   "info" : "Binary data empty",
   "resultCode" : "INVALID_DATA",
   "success" : false
}
```

We also see issues with putfile when attempting to send a series of putfiles, it looks like the crc32 values between mobile and core are not matching up.  I ran an external tool to confirm the value sent by the mobile is correct as seen below:

External tool output:
```
Files to signature:  1.
--------------------
[001/001] 
	Size:	187,370
	CRC-32:	12F8990F
	MD-5:	9bbce53156f5ae6d8569b8caf4230b0e
-------------------- FILE SIGNATURE COMPLETE --------------------
```


Message sent from mobile
```
DEBUG [23 Apr 2018 09:43:10,557][0x7f04c17fa700][ApplicationManager] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/application_manager_impl.cc:2279 ApplicationManagerImpl::ConvertMessageToSO: 			Message to convert: protocol 5; json {"fileType":"GRAPHIC_BMP","syncFileName":"myfile.pdf","crc":318281999}
```


Core checksum comparison
```
TRACE [23 Apr 2018 09:41:59,579][0x7f04c27fc700][Commands] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/commands/mobile/put_file_request.cc:209 commands::PutFileRequest::Run: Binary Data Size:  131072
TRACE [23 Apr 2018 09:41:59,579][0x7f04c27fc700][Commands] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/commands/mobile/put_file_request.cc:212 commands::PutFileRequest::Run: CRC32 SUM Received: 318281999
TRACE [23 Apr 2018 09:41:59,580][0x7f04c27fc700][Commands] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/commands/mobile/put_file_request.cc:214 commands::PutFileRequest::Run: CRC32 SUM Calculated: 1260619124
```

Core reply to mobile
```
DEBUG [23 Apr 2018 09:41:59,580][0x7f04c27fc700][ApplicationManager] /home/sdl/core_sdl_23Apr/sdl_core/src/components/application_manager/src/application_manager_impl.cc:2482 ApplicationManagerImpl::ConvertSOtoMessage: Convertion result: {
   "info" : "CRC Check on file failed. File upload has been cancelled, please retry.",
   "resultCode" : "CORRUPTED_DATA",
   "success" : false
}
```

**Comment by mrapitis** [comment]
@theresalech Ready for Livio review

**Comment by mrapitis** [comment]
@AByzhynar can you please update the main post to check off the unit test and atf test tasks as these tasks are complete.

**Comment by AByzhynar** [comment]
Rebuild required

**Comment by AByzhynar** [comment]
@mrapitis Thank you. Updated.

**Comment by AByzhynar** [comment]
Rebuild required

**Comment by mrapitis** [comment]
@theresalech please mark as ready for review. thanks

**Comment by mrapitis** [comment]
please disregard the rebuild comment

**Pull request merged**
