### PR TITLE
Fix failed thread_tests

### PR DESCRIPTION
**Pull request by pvvasilev**
Removed the detached thread tests

Related issue: [APPLINK-28086](https://adc.luxoft.com/jira/browse/APPLINK-28086)

### CODE REVIEW

**Comment by pvvasilev** [comment]
Please review @dtrunov @Kozoriz @AGritsevich @dev-gh @LuxoftAKutsan @anosach-luxoft

**Comment by AGritsevich** [comment]
@OHerasym, please review.

**Comment by OHerasym** [comment]
@pvvasilev , Please run this command: ./utils_test --gtest_repeat=5000 --gtest_break_on_failure --gtest_filter="ThreadOption*" . is there some fails?

**Comment by AGritsevich** [comment]
@pvvasilev, take attention, that your build fail on tests.

**Comment by pvvasilev** [comment]
@OHerasym I ran them a million times - no fails.

**Comment by pvvasilev** [comment]
@Anatoliy-Leshin @dtrunov Progress suspended because of issues with tests. This is the ticket to fix them https://adc.luxoft.com/jira/browse/APPLINK-28235

**Comment by pvvasilev** [comment]
This issue will be fixed in https://github.com/CustomSDL/sdl_panasonic/pull/552.

**Pull request closed without merging**
