### PR TITLE
Fix issue with throwing exception in ResumeCtrlTest

### PR DESCRIPTION
**Pull request by okozlovlux**
-fixed issue with throwing exception in tests:
   OnAppRegistrationEnd, OnAwake

Related to APPLINK-27147, APPLINK-27616

### CODE REVIEW

**Comment by okozlovlux** [comment]
@LevchenkoS @anosach-luxoft @vlantonov @pvvasilev @AByzhynar @wolfylambova22  please review

**Comment by LevchenkoS** [comment]
@okozlovlux, reviewed

**Comment by vlantonov** [comment]
@okozlovlux Reviewed

**Comment by AByzhynar** [comment]
@okozlovlux Please investigate if it's possible to use automatically reduced timer instead of hard coded timeout. Something which suits to you - can be found in GTest Framework

**Comment by AByzhynar** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Pull request merged**
