### PR TITLE
[WiP] Test crash

### PR DESCRIPTION
**Pull request by VVeremjova**

### CODE REVIEW

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by ovvasyliev** [comment]
Rebuild required

**Comment by LuxoftAKutsan** [comment]
Not actual

**Pull request closed without merging**
