### PR TITLE
Remove redundant tests

### PR DESCRIPTION
**Pull request by AMikhniev**
Removed sql_wrapper and qdb_wrapper tests form policy_test executable
	that copied same tests from utils_test executable.

### CODE REVIEW

**Comment by AMikhniev** [comment]
Please review: @malirod, @VVeremjova, @Kozoriz, @OHerasym
        Previous review #312

**Comment by malirod** [comment]
Fix the PR header. It's should be equal to the branch name

**Comment by AMikhniev** [comment]
@malirod It must be like LuxoftSDL:feature/Remove_redundant_tests or feature/Remove_redundant_tests?

**Comment by malirod** [comment]
Nope. It should be "Remove redundant tests". No underscores, no "feature".

**Comment by AMikhniev** [comment]
@malirod done.

**Comment by malirod** [comment]
Reviewed

**Comment by AMikhniev** [comment]
@AGaliuzov, can you merge this PR?

**Pull request merged**
