### PR TITLE
Genivi build fail with turned off logging

### PR DESCRIPTION
**Pull request by AMikhniev**
Added missed links to header files which added automatically when
logging turned on. Removed const bool is_media_app because it become
unused with log turned off.
Related to: [APPLINK-20489](https://adc.luxoft.com/jira/browse/APPLINK-20489)

### CODE REVIEW

**Comment by AMikhniev** [comment]
@VVeremjova @malirod @Kozoriz @OHerasym @AByzhynar please review.

**Comment by VVeremjova** [comment]
Reviewed

**Comment by OHerasym** [comment]
Reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Please specify which warning you're going to avoid

**Comment by anosach-luxoft** [comment]
Why have you called this branch `feature`?

**Comment by AMikhniev** [comment]
I did these changes to avoid build fails with disabled logging, which can be found on multiconfigural build target. These changes related to usual Task, not to Defect. Branch prefix should be changed to `hotfix/`?

**Comment by AMikhniev** [comment]
Warnings to avoid are:
- `/sdl_core/src/components/application_manager/src/commands/mobile/perform_audio_pass_thru_request.cc:301:21: error: ‘strlen’ was not declared in this scope if (strlen(str) && !CheckSyntax(str)) {`
- `/sdl_core/src/components/media_manager/include/media_manager/media_manager_impl.h:93:10: error: ‘map’ in namespace ‘std’ does not name a template type
     std::map<protocol_handler::ServiceType, MediaAdapterImplPtr> streamer_;`
- `/sdl_core/src/components/media_manager/include/media_manager/media_manager_impl.h:93:10: error: ‘map’ in namespace ‘std’ does not name a template type
     std::map<protocol_handler::ServiceType, MediaAdapterImplPtr> streamer_;`

**Comment by anosach-luxoft** [comment]
>I did these changes to avoid build fails with disabled logging, which can be found on multiconfigural >build target. These changes related to usual Task, not to Defect. Branch prefix should be changed to >hotfix/?

Yes. Rename branch after all participants reviewed. Note that you will have to create new pull request.

**Comment by anosach-luxoft** [comment]
BTW are you sure this changes should be merged to develop branch?

**Comment by AMikhniev** [comment]
I forked from [develop](https://github.com/LuxoftSDL/sdl_core/tree/develop). So if I try to send PR to master, I will need to resolve too much merge conflicts, because with my commits will be sended tons of other not merged commits from develop.

**Comment by OHerasym** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Comment by AMikhniev** [comment]
@VVeremjova @malirod @Kozoriz @OHerasym @AByzhynar please review.

**Comment by AMikhniev** [comment]
Changes moved to https://github.com/smartdevicelink/sdl_core/pull/359

**Pull request closed without merging**
