### PR TITLE
Fix SIGSEGV Crash subscribed_data

### LINKED ISSUE #3172: CCB: Fix SIGSEGV Crash subscribed_data
### Bug Report
SmartDeviceLink crash with SIGSEGV

### Detailed analysis:
unprotected access to the VehicleInfoAppExtension::subscribed_data from different threads

##### Reproduction Steps
1. Start SDL, HMI, connect Mobile
2. Register app
3. Perform multiple RPC scenarios and send OnVehicleDataNotification
4. Observe behavior

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed
[bt.txt](https://github.com/smartdevicelink/sdl_core/files/3932241/bt.txt)

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

### PR DESCRIPTION
**Pull request by zhouxin627**
Fixes #3172 #3162 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by manual testing

### Summary
There is a time interval between registering an application and adding `VehicleInfoAppExtension`,
and then registering a new App when you already subscribe to the Vehicle and have an information notification, because the App object for `QueryInterface()` already exists, but `VehicleInfoAppExtension` is not Added yet. So we add judgment protection for Invalid object usage. 
image

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
Looks like  that automated script that can reproduce the issue with some probability can be created .

**Comment by zhouxin627** [comment]
Hi @LuxoftAKutsan, thank you for your comment. We also considered to register the app first and then access the vehicle data of the app. The method is `RegisterApplication`、`AddExtension` first, and then `QueryInterface`, but the changing of timing sequence has a great impact on the existing design. Therefore, using NULL object protection can also solve the crash problem. And It is also correct not to send `OnVehicleData` notification when the registration process is not over. It is a failsafe scene. It also can be covered by the current modification scheme. Based on the above points, we believe that temporary solutions can solve this problem.

**Comment by zhouxin627** [comment]
Hi @LuxoftAKutsan, do you have a plan of making a PR to fix this issue.

**Comment by LuxoftAKutsan** [comment]
Possible fix  for https://github.com/smartdevicelink/sdl_core/issues/3162 
is available in SYNC4
Unfortunately it is not the approach that I was described in my previous comment.
Not sure if this changes will come into 7.0 .
Here is the diff 

[diff.txt](https://github.com/smartdevicelink/sdl_core/files/5097847/diff.txt)

**Comment by IGapchuk** [comment]
Hi @zhouxin627 ! We believe that https://github.com/smartdevicelink/sdl_core/pull/3430#issuecomment-676530924 is not full fix diff and we can provide the additional diff with changes for safely work with AppExtensions. Please, take a look at attached
[bugfix_3172_3162.txt](https://github.com/smartdevicelink/sdl_core/files/5246340/bugfix_3172_3162.txt). We believe it will be helpful.
If you have some additional questions or suggestions feel free to share them with us. Thank you!

**Comment by JackLivio** [comment]
@zhouxin627 @LuxoftAKutsan 

I am working on a fix to resolve this issue. I have reordered the app registration process slightly to add the plugins earlier to an app instance. The app will not be accessible by the applications accessor until all of the plugins have been added. This should prevent the crashes seen by missing app on the plugin level.

https://github.com/smartdevicelink/sdl_core/pull/3526/files

Separate note:

I attempted to resolve the issue seen here: https://github.com/smartdevicelink/sdl_core/pull/3428

But INVALID_ENUM plays an important roll in the app resumption process, especially with processing widget windows during resumption. The fix became to messy and i offered a simpler solution for that crash in the other pr.

**Comment by LuxoftAKutsan** [comment]
Looks like Jacks #3526 should fix this particular issue. 

But the root cause is more global and in the future, we will work on better documentation and reworking application registration.

The main problem is that there are many activities that need to be done during app registration (Resumption, update policy, add to plugins, to applicaiton_manager,  HMI notification, etc ... ). 
Some of this activities may prevent registration, some of them need to be done after another. 
We do not have a picture of the application registration sequence. 

We need to create appropriate documentation with list of activities that need to be done on app registration, there order, and dependencies.
Create separate events for plugins to create app extension and to notify a plugin that app is finally registered. 
Make an application accessible for external events only after the full registration cycle will be finished.

**Comment by JackLivio** [comment]
Closing in favor of #3526

**Pull request closed without merging**
