### PR TITLE
Mobile API aligning with latest Ford version

### PR DESCRIPTION
**Pull request by dev-gh**
Aligning with https://adc.luxoft.com/svn/APPLINK/doc/technical/requirements/FORD%20API/AppLink_Mobile_API_v4_x%20_withAppInfo_29Apr2016.xml

### CODE REVIEW

**Comment by dev-gh** [comment]
@anosach-luxoft @VProdanov @OHerasym @AGaliuzov @AByzhynar 
Please review

**Comment by AByzhynar** [comment]
Reviewed

**Comment by dev-gh** [comment]
@anosach-luxoft @VProdanov @OHerasym @AGaliuzov
Gentle reminder

**Comment by pestOO** [comment]
@dev-gh, shall be xml version updated according [agreements](https://adc.luxoft.com/confluence/display/APPLINK/Versioning+of+MOBILE_API+for+Genivi)?

**Comment by dev-gh** [comment]
@pestOO 
We agreed to make version changes only if that is specified explicitly in ticket by BA team.

**Comment by OHerasym** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by VProdanov** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
After merging this pull request coverage decreed up tp 60%

**Comment by mrapitis** [comment]
We are concerned that RAI requests are failing when parameters like carrier have empty string parameters in the device info.  Existing versions of the mobile proxies automatically populate this info.

**Pull request merged**
