### PR TITLE
Feature/format code and change clang format config to cpp03 std

### PR DESCRIPTION
**Pull request by AByzhynar**
Formatted code according C++03 Standard
Changed clang-format config to use C++03 Standard
Delete redundant notifications recipient from Travis CI

Related: [APPLINK-26587](https://adc.luxoft.com/jira/browse/APPLINK-26587)

### CODE REVIEW

**Comment by AByzhynar** [comment]
@okozlovlux @LevchenkoS @nk0leg @dev-gh @VVeremjova Please review

**Comment by okozlovlux** [comment]
@AByzhynar , reviewed

**Comment by LevchenkoS** [comment]
@AByzhynar, reviewed.

**Comment by dev-gh** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@AByzhynar Reviewed

**Comment by nk0leg** [comment]
@AByzhynar Reviewed

**Pull request merged**
