### PR TITLE
Prevent resumption of default keyboard properties after reset

### LINKED ISSUE #3610: SDL resumes App's defined keyboard properties if they have been reset
### Bug Report
SDL resumes App's defined keyboard properties if they have been reset

##### Reproduction Steps
1. App is registered
2. App sends `SetGlobalProperties` with some non-default values for `KeyboardProperties`
3. App sends `ResetGlobalProperties` for `KEYBOARDPROPERTIES`
=> SDL resets `KeyboardProperties` to default ones
4. App unexpectedly disconnects and reconnects

##### Expected Behavior
SDL does:
  - Start data resumption process
  - Not send `KeyboardProperties` within `UI.SetGlobalProperties` request to HMI

##### Observed Behavior
SDL does:
 - send App's defined keyboard properties

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/tree/develop (49bf5df)
* Testing Against: ATF

##### Test Case, Sample Code, and / or Example App
 - ATF Script: [3610.lua.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5716744/3610.lua.tar.gz)
 - Report and Logs: [2020-12-18_11-08-14.652_3610.tar.gz](https://github.com/smartdevicelink/sdl_core/files/5716747/2020-12-18_11-08-14.652_3610.tar.gz)

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #3610 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Covered by ATF test script

### Summary
There is an issue when after reset of keyboard properties previously saved values are still resumed instead of default ones. Root cause of this situation is ignoring of keyboard properties cache during reset of keyboard properties. Previously this cache wasn't emptied during reset, so it continued to store outdated application defined data. This cache is also used as data source for resumption, that's why we need to empty this cache after reset, because we don't need to re-send requests with default keyboard properties.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ychernysheva** [comment]
@JackLivio This PR is ready for review.
Thank you!

**Comment by JackLivio** [comment]
@ychernysheva We are including a similar fix in this pr: https://github.com/smartdevicelink/sdl_core/pull/3635/files

**Comment by ychernysheva** [comment]
@JackLivio Thank you for your response! It seems that after proposed changes from https://github.com/smartdevicelink/sdl_core/pull/3635/files this defect is still actual (I've checked it locally). Maybe it's possible to replace https://github.com/smartdevicelink/sdl_core/pull/3635/files#diff-59bdfbd55b32b2dae488584440e0d7a594ca6176c26d15fbf479deecc8a7f999L410 with https://github.com/smartdevicelink/sdl_core/pull/3633/files#diff-59bdfbd55b32b2dae488584440e0d7a594ca6176c26d15fbf479deecc8a7f999L410 ?

**Comment by JackLivio** [comment]
@ychernysheva Thank you, reconsidering this pr. Could maybe explain why clearing the map doesnt work the same as setting the value to null?

**Comment by ychernysheva** [comment]
@JackLivio If we clear this map, we will have following parameter in UI request during resumption: `"keyboardProperties":{}`.
I guess that it is caused by the next code inside of resumption_data_db.cc file: https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/src/resumption/resumption_data_db.cc#L2449

**Comment by JackLivio** [comment]
@ychernysheva Thank you for pointing that out.

**Comment by JackLivio** [comment]
I confirmed the empty object issue caused by our previous fix, but im not sure this fix includes all necessary changes for the problem.

1. I had a test app configured to use the AZERTY keyboard. 
2. Sent a resetGlobalProperties, here is the msg received by hmi 👍 
Screen Shot 2021-02-18 at 1 46 57 PM
3. I reset and resume the app with a valid hashid and this is the setGlobalProperties message received by the hmi  (maybe👎 ?)
Screen Shot 2021-02-18 at 1 47 10 PM

Shouldnt the messages in screenshot's 2&3 be the same?

**Review by JackLivio — APPROVED** [review]

**Pull request merged**
