### PR TITLE
Update build dependencies in CMakeLists.txt files

### PR DESCRIPTION
**Pull request by orhan-mehmedov**
Update build dependencies in order to be able
to build in parallel mode, for example:
make -j4
No source code changed.

Related to [APPLINK-25547](https://adc.luxoft.com/jira/browse/APPLINK-25547).

### CODE REVIEW

**Comment by orhan-mehmedov** [comment]
Please review,
@vlantonov, @AGaliuzov, @LevchenkoS, @anosach-luxoft, @dev-gh, @VVeremjova

**Comment by orhan-mehmedov** [comment]
Hint: you can try it locally on your machines. Good to know if there is a problem during real build.

**Comment by vlantonov** [comment]
@orhan-mehmedov Reviewed.

**Comment by AGaliuzov** [comment]
@orhan-mehmedov Reviewed

**Comment by LevchenkoS** [comment]
@orhan-mehmedov, reviewed.

**Comment by dev-gh** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by VVeremjova** [comment]
@orhan-mehmedov Reviewed

**Pull request merged**
