### PR TITLE
Add WARNINGS resultCode in TTSSpeak alert request

### PR DESCRIPTION
**Pull request by OHerasym**
Related:
       APPLINK-15711

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review: @malirod, @VVeremjova , @Kozoriz, @AMikhniev

**Comment by AMikhniev** [comment]
reviewed

**Comment by pestOO** [comment]
Please use [the links](https://guides.github.com/features/mastering-markdown/#examples) to [the tickets](https://adc.luxoft.com/jira/browse/APPLINK-17513)  :+1:

**Comment by Kozoriz** [comment]
reviewed

**Pull request merged**
