### PR TITLE
Fix defect consumer_friendly_messages are deleted from PT

### PR DESCRIPTION
**Pull request by pold500**
* Changed files
 src/components/policy/policy_external/src/sql_pt_representation.cc
 Removed deletion of the table if param consumer_friendly_messages is omitted

### CODE REVIEW

**Comment by pold500** [comment]
@LuxoftAKutsan please review
@VVeremjova please review
@dcherniev please review

**Comment by pold500** [comment]
Rebuild required

**Comment by dcherniev** [comment]
@pold500 You have made change to 'sql_pt_representation.cc' file only in 'policy_external' folder, so does this change exclusive to 'EXTERNAL_PROPRIETARY' configuration? what about 'policy_regular' folder (it contains the same file in it)? Have you tested your ATF scripts in 'PROPRIETARY' configuration?

**Comment by pold500** [comment]
@dcherniev  I've clear specification in defect description that I should fix that only on EXTERNAL_PROPRIETARY.

**Comment by pold500** [comment]
@LuxoftAKutsan please merge this pull request

**Pull request merged**
