### PR TITLE
Hotfix/remove redundant test main

### PR DESCRIPTION
**Pull request by OHerasym**
Deleted redundant main test files, deleted unused test directory, moved tests to 3rd-party-static & tools/test. 

Related:
             APPLINK-20109

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review: @malirod, @AByzhynar , @Kozoriz, @VVeremjova

**Comment by malirod** [comment]
I see two huge commits with the same messages. I think this is not right. Squash them.
I see that deleted 9162 lines, and added only 28. Is this correct? Are you sure that it's right to delete all those files?

**Comment by AByzhynar** [comment]
Reviewed

**Comment by OHerasym** [comment]
@malirod , Yes, all files were in test folder (not used now). Same things are already changed in develop branch, I just do same task in master. Two commits have different commit messages, they have same title. One commit delete files. Second commit add files to tools/test/ & 3rd-party-static/test/.
Is it will be correct squash them?

**Comment by malirod** [comment]
I've looked briefly these commits and I cannot see any logic in them. So I think it's ok to squash. This way we would have one huge "illogical" commit.

**Comment by OHerasym** [comment]
@malirod , Done

**Comment by malirod** [comment]
Reviewed

**Comment by malirod** [comment]
@OHerasym, I have doubts that you've done  the right thing with this PR. As far as I understand the APPLINK-20109, your task was to choose one file from two available and delete it. I don't think that deletion of the big amount of tests is the right way to go.
Even if it's ok to delete those tests (this should be confirmed by someone), I propose to split this PR into two. One will resolve the APPLINK-20109. And another will drop redundant tests(if requred).

**Comment by VVeremjova** [comment]
policy_table_validator should be also moved in tools

**Comment by OHerasym** [comment]
@malirod , @VVeremjova , Added policy_table_validator. Created 3 commits:
 1)Remove reduntant test main files.
2) Add tests in tools & 3rd-party-static.
3) Delete unused folder test

**Comment by Kozoriz** [comment]
Reviewed

**Comment by VVeremjova** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
