### PR TITLE
Delete part of SDL code that uses AVAHI

### PR DESCRIPTION
**Pull request by OHerasym**
Delete part of SDL code that uses AVAHI
Related:
        [APPLINK-14640] (https://adc.luxoft.com/jira/browse/APPLINK-14640)

### CODE REVIEW

**Comment by OHerasym** [comment]
Please review: @malirod , @AMikhniev , @VVeremjova, @Kozoriz, @AByzhynar

**Comment by AByzhynar** [comment]
Reviewed

**Comment by Kozoriz** [comment]
Reviewed

**Comment by VVeremjova** [comment]
Reviewed

**Comment by AMikhniev** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Pull request merged**
