### PR TITLE
Fixes update of application list for SDL4 

### PR DESCRIPTION
**Pull request by dev-gh**
Changes allow to simultaneously represent same registered and to_be_registered applications from different devices.

Closes-bug: APPLINK-11307

### CODE REVIEW

**Comment by dev-gh** [comment]
@AGaliuzov @LuxoftAKutsan @dtrunov 
Please review

**Comment by dtrunov** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
@justinjdickow, could you please suggest the proper behaviour for merging this PR:

1. From the one hand it fixes the QUERY_APP functionality which is a part of currently released code
2. From the other hand it changes reumption functionality which could lead to regression

So I would suggest to rather merge this to `develop` instead of `master`

Don't you mind about that?

**Comment by AGaliuzov** [comment]
@justinjdickow? have you any thought on this?

**Comment by justinjdickow** [comment]
Is it possible to split into a hot fix for QUERY_APP and a change into develop for resumption?

**Comment by LuxoftAKutsan** [comment]
reviewed

**Comment by dev-gh** [comment]
@justinjdickow 
That's possible. However resumption issue almost blocks using of original scenario, i.e. same SDL4 app from different devices because of assigning of the same 'app_id' field (used between SDL and system) to applications with same application id (from RAI). That in turn causes web-HMI to show only one application.
So, please confirm, if you want us to deliver these commits to separate branches anyway.

**Comment by AGaliuzov** [comment]
@justinjdickow have you any thought on this?

**Comment by AGaliuzov** [comment]
@justinjdickow could you answer please?

**Comment by dev-gh** [comment]
@justinjdickow 
Could you comment on [that](https://github.com/smartdevicelink/sdl_core/pull/450#issuecomment-206713317)?

**Comment by dev-gh** [comment]
There is upcoming 4.1.0 release which already has resumption changes, so another pull request will be sent to this new release branch and later on will be merged to master.

**Pull request closed without merging**
