### PR TITLE
Fix undefined behavior in auto trace test

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
@AByzhynar  please review

### CODE REVIEW

**Comment by AByzhynar** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
@anosach-luxoft  please merge

**Comment by LuxoftAKutsan** [comment]
@okozlov @malirod @Anatoliy-Leshin  Please review

**Comment by Anatoliy-Leshin** [comment]
Reviewed

**Comment by LuxoftAKutsan** [comment]
@okozlov @malirod  Please review

**Pull request closed without merging**
