### PR TITLE
Add QT5 build support for travis CI and verify SDL core with DBUS sup…

### PR DESCRIPTION
**Pull request by chinlin0924**
…port
1. Add Qt 5.2 support for travis CI
2. Build with dbus & json to ensure lastest code is not broken for both build
   (folder buld_dbus for dbus version and build for json/websocket version)
3. Add the missed interface on QT_HMI_API.xml for the compile issue
   on DialNumber RPC call

### CODE REVIEW

**Comment by chinlin0924** [comment]
@justinjdickow can you help review?

**Comment by justinjdickow** [comment]
@AGaliuzov Can you review?

**Comment by AGaliuzov** [comment]
@justinjdickow looks fine. The only question why to the master?

**Comment by BrandonHe** [comment]
I confuse why need set HMI2 parameter in travis? It can be configured in CMakeLists.txt file as optional. If it's necessary, why qt version is 5.2, you know, different version has different features, such as qt V5.3 support WinCE port, considered by compatibility? Also, it will be better if export /opt/qt52/bin/qt52-env.sh as environment variable.

**Comment by BrandonHe** [comment]
Here is the SDL on Linux with Qt [wiki](https://github.com/smartdevicelink/sdl_core/wiki/SDL-on-Linux-with-QT)

**Comment by vortexdyne** [comment]
@BrandonHe this change is to check if SDL core for both dbus version or websocket(json) is compiled correctly without any errors in CI process. In order to enable the DBUS version, HMI2 parameter is set according to the https://github.com/smartdevicelink/sdl_core/pull/568#issuecomment-224261997
I only can find minimal Qt 5.2 package environment installation for Travis, that doesn't affect the results to use Qt 5.2. Or is there any reason not to use Qt 5.1? I know there are different features available between QT versions and Qt 5.2 provides more features than Qt 5.1 at least.
It is a good suggestion to export /opt/qt52/bin/qt52-env.sh as environment variable.
thanks!

**Comment by BrandonHe** [comment]
@vortexdyne OK, thanks!

**Comment by vortexdyne** [comment]
@justinjdickow most developers may clone latest code from master, and create branch for it to add new features. In order to make travis check works in all possible branch, so I choose to add this travis change to master.

**Comment by chinlin0924** [comment]
@justinjdickow most developers may clone latest code from master branch, and create his feature branch for adding some changes. In order to make the changes to check if they cause compiler error in both dbus or json version, so I choose to push it into master branch.

**Comment by LuxoftAKutsan** [comment]
@chinlin0924 main problem of travis CI currently is that free version does not provide enough resources even for compiling SDL in one configuration, unit tests run and coverage collecting. Is there some plans to fix this issue?

**Comment by jacobkeeler** [comment]
Closing due to the removal of the QT HMI

**Pull request closed without merging**
