### PR TITLE
Add email notifications to responsible persons

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Add notifications to

Configuration management responsible persons:
 - AKutsan@luxoft.com
 - AByzhynar@luxoft.com

Managers:
 - NSnitsar@luxoft.com
 - RMalynovskyi@luxoft.com
 - MGhiumiusliu@luxoft.com

Developers with write access:
 - AGaliuzov@luxoft.com
 - ANosach@luxoft.com

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@malirod 
@AGaliuzov 
@anosach-luxoft 
@AByzhynar 
Please review

**Comment by malirod** [comment]
reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by AGaliuzov** [comment]
reviwed

**Comment by LuxoftAKutsan** [comment]
@AGaliuzov please meerge. Build fails not because of this changes

**Pull request merged**
