### PR TITLE
Update MOBILE API to version 6.0.0

### PR DESCRIPTION
**Pull request by jacobkeeler**
Revision to #2927

This PR is **ready** for review.

### Risk
This PR makes **major** API changes.

### Summary
Update MOBILE API to version 6.0.0

##### Enhancements
* Update MOBILE API to version 6.0.0

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@JackLivio @jacobkeeler 
After merging this PR

All new and modified parameters in the following proposal will have `since` value `6.0` :

 - Adding GPS Shift support
 - Pixel density and Scale
 - Support running the same app from multiple devices at the same time
 - Remote Control - Radio and Climate Parameter Update
 - Service Status Update to HMI
 - RPC message protection
 - Power to the Box
 - Widget support
 - Allow Multiple Modules per Module Type
 - SDL-passenger-mode

I have a question related to backward compatibility.

Because of major version change, we can avoid deprecating old versions of modified parameters, and remove them.

It is a significant point mostly for the following proposals :
 - Support running the same app from multiple devices at the same time
 - Remote Control - Radio and Climate Parameter Update
 - Widget support

This proposal contains a modification of existing params.
Including proposal in minor release would require keeping backward compatibility and marking old parameter versions as deprecated.
Including proposal in major version allow us to simplify implementation and remove deprecated parameters.

**Comment by AByzhynar** [comment]
@jacobkeeler Don't we need to change related parts in sdl_core c++ code like: https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/utils/src/semantic_version.cc

**Comment by JackLivio** [comment]
@AByzhynar No those do not need to be changed. They are used in defining specific behavior for core/mobile/hmi communication depending on the negotiated rpc verision. There might need to be a rpc_version_6 introduced if we want to be able to support backwards compatibility for pre 6.0 mobile apps while creating breaking changes for future versions.

**Comment by JackLivio** [comment]
@LuxoftAKutsan As far as I know we want to keep them deprecated in 6.0 so those params have a period of deprecation and align with the accepted proposals. If you strongly believe they should be removed with no deprecation, there would need to be revisions made to those proposals.

**Comment by LuxoftAKutsan** [comment]
@JackLivio Do we have any clear `check list` of reasons to remove a parameter, but not deprecate it? 
From my perspective : 
 - The parameter is not widely used by existing mobile apps.
 - All signficant mobile apps that used this parameter confirmed that mobile application will be updated to support new version
 - Overhead for supporting old parameter is to big ( BTW this point is not realy specific)

**Comment by LuxoftAKutsan** [comment]
@JackLivio @jacobkeeler  And I have additional question regarding deprecated methods in C++ interfaces. Can the be deleted with an increasing major release version?

**Comment by JackLivio** [comment]
@LuxoftAKutsan We have a different stance on Core changes. We are ok with just removing public methods in the Core code without deprecating in this major version change release.

**Pull request merged**
