### PR TITLE
Add double datatype in API

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Add supporting of generation API with Double Data types

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@anosach-luxoft @AGaliuzov @malirod please review

**Comment by LuxoftAKutsan** [comment]
@OHerasym  please also review

**Comment by anosach-luxoft** [comment]
Reviewed

**Comment by malirod** [comment]
Reviewed

**Comment by tpulatha** [comment]
Why would you do integer, float and double in the same elif? Doesn't it make more sense to split them out in single elif to create a cleaner implementation?

**Comment by LuxoftAKutsan** [comment]
@AGaliuzov  please merge it

**Comment by AGaliuzov** [comment]
@LuxoftAKutsan for me it looks like the bugfix, why you have decided that this is feature?

**Pull request merged**
